
package itp;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Customer_Service_fix extends javax.swing.JInternalFrame {
    Connection con= null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    String nic = null;
    
    public Customer_Service_fix() {
        initComponents();
        con = DBconnect.connect();
        
        txtNOI1.setEnabled(false);
        txtNOI2.setEnabled(false);
        txtNOI3.setEnabled(false);
        txtNOI4.setEnabled(false);
        txtNOI5.setEnabled(false);
        txtDes1.setEnabled(false);
        txtDes2.setEnabled(false);
        txtDes3.setEnabled(false);
        txtDes4.setEnabled(false);
        txtDes5.setEnabled(false);
        
                      try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM fixing_service");
            while (rs.next()) {

                String ab = rs.getString("fixing_id");
                int ps = Integer.parseInt(ab);
                int ks = ps+1;
                 String ks1 = String.valueOf(ks);
                 lblSID.setText(ks1);
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Service ID Fail");
            
        }  
         Calendar now = Calendar.getInstance();
		int month = now.get(Calendar.MONTH); 
                int date = now.get(Calendar.DATE); 
                int year = now.get(Calendar.YEAR);
                String Date = year + "-" + month + "-" + date;
                lblCDate.setText(Date);
                
                now.add(Calendar.YEAR,1);
		int amonth = now.get(Calendar.MONTH);
                int adate = now.get(Calendar.DATE); 
                int ayear = now.get(Calendar.YEAR);
                String aDate = ayear + "-" + amonth + "-" + adate;
                lblWEDate.setText(aDate);
                table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFName = new javax.swing.JLabel();
        lblLName = new javax.swing.JLabel();
        lblTP = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCDate = new javax.swing.JLabel();
        lblWEDate = new javax.swing.JLabel();
        lblFSL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtCID = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cmb1 = new javax.swing.JComboBox<>();
        cmb2 = new javax.swing.JComboBox<>();
        cmb3 = new javax.swing.JComboBox<>();
        cmb4 = new javax.swing.JComboBox<>();
        cmb5 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblIN1 = new javax.swing.JLabel();
        lblIN2 = new javax.swing.JLabel();
        lblIN3 = new javax.swing.JLabel();
        lblIN4 = new javax.swing.JLabel();
        lblIN5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtNOI1 = new javax.swing.JTextField();
        txtNOI2 = new javax.swing.JTextField();
        txtNOI3 = new javax.swing.JTextField();
        txtNOI4 = new javax.swing.JTextField();
        txtNOI5 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtDes1 = new javax.swing.JTextField();
        txtDes2 = new javax.swing.JTextField();
        txtDes3 = new javax.swing.JTextField();
        txtDes4 = new javax.swing.JTextField();
        txtDes5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        lblSID = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setBorder(null);
        setForeground(java.awt.Color.white);
        setTitle("Curtains Fixing Services");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);
        setFocusCycleRoot(false);
        setFocusable(false);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/itp/bs.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(1050, 640));
        setMinimumSize(new java.awt.Dimension(1050, 640));
        setPreferredSize(new java.awt.Dimension(1050, 640));
        setVisible(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(332, 191));
        jPanel1.setMinimumSize(new java.awt.Dimension(332, 191));

        jLabel1.setText("Customer First Name   ");

        jLabel2.setText("Customer Last Name   ");

        jLabel3.setText("Customer Telephone   ");

        jLabel4.setText("Customer Address       ");

        jLabel5.setText("Current Date               ");

        jLabel6.setText("Warranty expiry Date ");

        jLabel7.setText("Free Services Left       ");

        lblFName.setEnabled(false);

        lblLName.setEnabled(false);

        lblTP.setEnabled(false);

        lblAddress.setEnabled(false);

        lblCDate.setEnabled(false);

        lblWEDate.setEnabled(false);

        lblFSL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFSL.setForeground(new java.awt.Color(153, 0, 0));
        lblFSL.setText("3");
        lblFSL.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblWEDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(lblCDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFSL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblFName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblLName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblCDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblWEDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblFSL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(332, 49));
        jPanel2.setMinimumSize(new java.awt.Dimension(332, 49));

        jLabel8.setText("Customer ID  :");

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.setToolTipText("Do you want to search customer details ?");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtCID.setToolTipText("please enter customer ID here");
        txtCID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCIDKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jButton1)
                    .addComponent(txtCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setMaximumSize(new java.awt.Dimension(663, 223));
        jPanel8.setMinimumSize(new java.awt.Dimension(663, 223));

        jLabel16.setText("Fixing Details");

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setMaximumSize(new java.awt.Dimension(100, 183));
        jPanel9.setMinimumSize(new java.awt.Dimension(100, 183));

        jLabel17.setText("Item ID");

        cmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1ActionPerformed(evt);
            }
        });

        cmb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb2ActionPerformed(evt);
            }
        });

        cmb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb3ActionPerformed(evt);
            }
        });

        cmb4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb4ActionPerformed(evt);
            }
        });

        cmb5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb1, 0, 76, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmb3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmb4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmb5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(13, 13, 13)
                .addComponent(cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(cmb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(cmb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(cmb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(cmb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setMaximumSize(new java.awt.Dimension(116, 123));
        jPanel3.setMinimumSize(new java.awt.Dimension(116, 123));

        jLabel18.setText("Item Name");

        lblIN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN1.setEnabled(false);

        lblIN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN2.setEnabled(false);

        lblIN3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN3.setEnabled(false);

        lblIN4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN4.setEnabled(false);

        lblIN5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN5.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel18)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIN3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIN2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIN4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIN5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(lblIN1)
                .addGap(18, 18, 18)
                .addComponent(lblIN2)
                .addGap(18, 18, 18)
                .addComponent(lblIN3)
                .addGap(18, 18, 18)
                .addComponent(lblIN4)
                .addGap(18, 18, 18)
                .addComponent(lblIN5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setMaximumSize(new java.awt.Dimension(106, 175));
        jPanel4.setMinimumSize(new java.awt.Dimension(106, 175));

        jLabel19.setText("No of Items used");

        txtNOI1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNOI1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNOI1KeyTyped(evt);
            }
        });

        txtNOI2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNOI2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNOI2KeyTyped(evt);
            }
        });

        txtNOI3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNOI3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNOI3KeyTyped(evt);
            }
        });

        txtNOI4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNOI4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNOI4KeyTyped(evt);
            }
        });

        txtNOI5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNOI5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNOI5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNOI1)
                    .addComponent(txtNOI2)
                    .addComponent(txtNOI3)
                    .addComponent(txtNOI4)
                    .addComponent(txtNOI5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNOI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNOI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNOI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNOI4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNOI5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setMaximumSize(new java.awt.Dimension(299, 175));
        jPanel5.setMinimumSize(new java.awt.Dimension(299, 175));

        jLabel20.setText("Description");

        txtDes1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtDes2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtDes3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtDes4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtDes5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDes2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDes3)
                    .addComponent(txtDes4)
                    .addComponent(txtDes5)
                    .addComponent(txtDes1))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel20)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDes5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Report");
        jButton2.setToolTipText("Do you want to save records ?");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.setToolTipText("Reset every things");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fixing ID", "Customer ID", "Date", "Warranty Left", "Warranty Expiry", "Item No", "Qty", "Description", "Item No", "Qty", "Description", "Item No", "Qty", "Description", "Item No", "Qty", "Description", "Item No", "Qty", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        jLabel26.setText("Service ID         :");

        lblSID.setEnabled(false);

        jButton5.setBackground(new java.awt.Color(255, 153, 255));
        jButton5.setText("Demo");
        jButton5.setToolTipText("Domo to test");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 51, 51));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Refresh");
        jButton6.setToolTipText("Refresh database");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 51, 51));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Delete");
        jButton7.setToolTipText("Do you want to delete previous records ?");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(lblSID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNOI1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNOI1KeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtNOI1KeyTyped

    
    public void table() {

        DefaultTableModel dtf = (DefaultTableModel) jTable1.getModel();
        dtf.setRowCount(0);

        try {
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
            
            rs=s.executeQuery("SELECT * FROM fixing_service");

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("fixing_id"));
                v.add(rs.getString("customer_id"));
                v.add(rs.getDate("dates"));
                v.add(rs.getString("warranty_left"));
                v.add(rs.getDate("warranty_expiry"));
                v.add(rs.getString("item_no1"));
                v.add(rs.getString("qty1"));
                v.add(rs.getString("description1"));
                v.add(rs.getString("item_no2"));
                v.add(rs.getString("qty2"));
                v.add(rs.getString("description2"));
                v.add(rs.getString("item_no3"));
                v.add(rs.getString("qty3"));
                v.add(rs.getString("description3"));
                v.add(rs.getString("item_no4"));
                v.add(rs.getString("qty4"));
                v.add(rs.getString("description4"));
                v.add(rs.getString("item_no5"));
                v.add(rs.getString("qty5"));
                v.add(rs.getString("description5"));
                
                            
                dtf.addRow(v);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Table load Fail");
        }
    }
    
    
    
    private void txtNOI2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNOI2KeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtNOI2KeyTyped

    public void Reset() {
        txtCID.setText("");

        lblFName.setText("");
        lblLName.setText("");
        lblTP.setText("");
        lblAddress.setText("");

        lblIN1.setText("");
        lblIN2.setText("");
        lblIN3.setText("");
        lblIN4.setText("");
        lblIN5.setText("");
        txtNOI1.setText("");
        txtNOI2.setText("");
        txtNOI3.setText("");
        txtNOI4.setText("");
        txtNOI5.setText("");
        txtDes1.setText("");
        txtDes2.setText("");
        txtDes3.setText("");
        txtDes4.setText("");
        txtDes5.setText("");
        cmb1.setSelectedIndex(0);
        cmb2.setSelectedIndex(0);
        cmb3.setSelectedIndex(0);
        cmb4.setSelectedIndex(0);
        cmb5.setSelectedIndex(0);
    }
    
    private void txtNOI3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNOI3KeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtNOI3KeyTyped

    private void txtNOI4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNOI4KeyTyped
       char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtNOI4KeyTyped

    private void txtNOI5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNOI5KeyTyped
       char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtNOI5KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (txtCID.getText().isEmpty()){
            jLabel7.setText("Invalid");
        }
        
        else if (lblFName.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "Please select valid Customer");   
        }
        
        else {    
            
             try {
               Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
                rs = s.executeQuery("SELECT nic FROM customer WHERE id='"+txtCID.getText()+ "'");
                while (rs.next()) {
                    
                  nic =  rs.getString("nic");
                    
                }
          } catch (Exception e) {
              
              JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            }
            
            
        String a = lblSID.getText();
        String b = txtCID.getText();
        String c = lblFName.getText();
        String d = lblLName.getText();
        String e = lblTP.getText();
        String f = lblAddress.getText();
        String g = lblFSL.getText();
        
        String h = (String) cmb1.getSelectedItem();
        String i = lblIN1.getText();
        String j = txtNOI1.getText();
        String k = txtDes1.getText();
        
        String h1 = (String) cmb2.getSelectedItem();
        String i1 = lblIN2.getText();
        String j1 = txtNOI2.getText();
        String k1 = txtDes2.getText();
        
        String h2 = (String) cmb3.getSelectedItem();
        String i2 = lblIN3.getText();
        String j2 = txtNOI3.getText();
        String k2 = txtDes3.getText();
        
        String h3 = (String) cmb4.getSelectedItem();
        String i3 = lblIN4.getText();
        String j3 = txtNOI4.getText();
        String k3 = txtDes4.getText();
        
        String h4 = (String) cmb5.getSelectedItem();
        String i4 = lblIN5.getText();
        String j4 = txtNOI5.getText();
        String k4 = txtDes5.getText();
        
         String jj89 = lblCDate.getText();
        String kk89 = lblWEDate.getText();
        
        Customer_fix_Report csf = new Customer_fix_Report(a,b,c,d,e,f,g,h,i,j,k,h1,i1,j1,k1,h2,i2,j2,k2,h3,i3,j3,k3,h4,i4,j4,k4,jj89,kk89,nic); 
        csf.setVisible(true);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Reset();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if(txtCID.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "Please Enter Customer ID");   
        }
        
        else {
         try {
               Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
                rs = s.executeQuery("SELECT * FROM customer WHERE id='"+txtCID.getText()+ "'");
                while (rs.next()) {
                    
                    lblFName.setText(rs.getString("first_name"));
                    lblLName.setText(rs.getString("last_name"));
                    lblTP.setText(rs.getString("contact_number"));
                    lblAddress.setText(rs.getString("address_line2"));
                    
                }
          } catch (Exception e) {
              
              JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            }
     
        } 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1ActionPerformed

boolean enable = cmb1.getSelectedItem().equals("Item 001") ||cmb1.getSelectedItem().equals("Item 002") || cmb1.getSelectedItem().equals("Item 003") || cmb1.getSelectedItem().equals("Item 004") || cmb1.getSelectedItem().equals("Item 005")|| cmb1.getSelectedItem().equals("Item 005")|| cmb1.getSelectedItem().equals("Item 006")|| cmb1.getSelectedItem().equals("Item 007")|| cmb1.getSelectedItem().equals("Item 008") ;
       txtNOI1.setEnabled(enable);
        txtDes1.setEnabled(enable);


        if(cmb1.getSelectedItem().toString()=="Item 001"){
            lblIN1.setText("Single Rod");}
        else if(cmb1.getSelectedItem().toString()=="Item 002"){
            lblIN1.setText("Double Rod");}
        else if(cmb1.getSelectedItem().toString()=="Item 003"){
            lblIN1.setText("Holdback");}
        else if(cmb1.getSelectedItem().toString()=="Item 004"){
            lblIN1.setText("Clip Ring");}
        else if(cmb1.getSelectedItem().toString()=="Item 005"){
            lblIN1.setText("Brass");}
        else if(cmb1.getSelectedItem().toString()=="Item 006"){
            lblIN1.setText("Flat Bar");}
        else if(cmb1.getSelectedItem().toString()=="Item 007"){
            lblIN1.setText("Single Rail");}
        else if(cmb1.getSelectedItem().toString()=="Item 008"){
            lblIN1.setText("Double Rail");}
        else {
            lblIN1.setText("----");}
    }//GEN-LAST:event_cmb1ActionPerformed

    private void cmb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb2ActionPerformed

        boolean enable = cmb2.getSelectedItem().equals("Item 001") ||cmb2.getSelectedItem().equals("Item 002") || cmb2.getSelectedItem().equals("Item 003") || cmb2.getSelectedItem().equals("Item 004") || cmb2.getSelectedItem().equals("Item 005")|| cmb2.getSelectedItem().equals("Item 005")|| cmb2.getSelectedItem().equals("Item 006")|| cmb2.getSelectedItem().equals("Item 007")|| cmb2.getSelectedItem().equals("Item 008") ;
       txtNOI2.setEnabled(enable);
        txtDes2.setEnabled(enable);
        
        if(cmb2.getSelectedItem().toString()=="Item 001"){
            lblIN2.setText("Single Rod");}
        else if(cmb2.getSelectedItem().toString()=="Item 002"){
            lblIN2.setText("Double Rod");}
        else if(cmb2.getSelectedItem().toString()=="Item 003"){
            lblIN2.setText("Holdback");}
        else if(cmb2.getSelectedItem().toString()=="Item 004"){
            lblIN2.setText("Clip Ring");}
        else if(cmb2.getSelectedItem().toString()=="Item 005"){
            lblIN2.setText("Brass");}
        else if(cmb2.getSelectedItem().toString()=="Item 006"){
            lblIN2.setText("Flat Bar");}
        else if(cmb2.getSelectedItem().toString()=="Item 007"){
            lblIN2.setText("Single Rail");}
        else if(cmb2.getSelectedItem().toString()=="Item 008"){
            lblIN2.setText("Double Rail");}
        else {
            lblIN2.setText("----");}
                                     
    }//GEN-LAST:event_cmb2ActionPerformed

    private void cmb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb3ActionPerformed

 boolean enable = cmb3.getSelectedItem().equals("Item 001") ||cmb3.getSelectedItem().equals("Item 002") || cmb3.getSelectedItem().equals("Item 003") || cmb3.getSelectedItem().equals("Item 004") || cmb3.getSelectedItem().equals("Item 005")|| cmb3.getSelectedItem().equals("Item 005")|| cmb3.getSelectedItem().equals("Item 006")|| cmb3.getSelectedItem().equals("Item 007")|| cmb3.getSelectedItem().equals("Item 008") ;
       txtNOI3.setEnabled(enable);
        txtDes3.setEnabled(enable);



        if(cmb3.getSelectedItem().toString()=="Item 001"){
            lblIN3.setText("Single Rod");}
        else if(cmb3.getSelectedItem().toString()=="Item 002"){
            lblIN3.setText("Double Rod");}
        else if(cmb3.getSelectedItem().toString()=="Item 003"){
            lblIN3.setText("Holdback");}
        else if(cmb3.getSelectedItem().toString()=="Item 004"){
            lblIN3.setText("Clip Ring");}
        else if(cmb3.getSelectedItem().toString()=="Item 005"){
            lblIN3.setText("Brass");}
        else if(cmb3.getSelectedItem().toString()=="Item 006"){
            lblIN3.setText("Flat Bar");}
        else if(cmb3.getSelectedItem().toString()=="Item 007"){
            lblIN3.setText("Single Rail");}
        else if(cmb3.getSelectedItem().toString()=="Item 008"){
            lblIN3.setText("Double Rail");}
        else {
            lblIN3.setText("----");}
                                    
    }//GEN-LAST:event_cmb3ActionPerformed

    private void cmb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb4ActionPerformed

 boolean enable = cmb4.getSelectedItem().equals("Item 001") ||cmb4.getSelectedItem().equals("Item 002") || cmb4.getSelectedItem().equals("Item 003") || cmb4.getSelectedItem().equals("Item 004") || cmb4.getSelectedItem().equals("Item 005")|| cmb4.getSelectedItem().equals("Item 005")|| cmb4.getSelectedItem().equals("Item 006")|| cmb4.getSelectedItem().equals("Item 007")|| cmb4.getSelectedItem().equals("Item 008") ;
       txtNOI4.setEnabled(enable);
        txtDes4.setEnabled(enable);


        if(cmb4.getSelectedItem().toString()=="Item 001"){
            lblIN4.setText("Single Rod");}
        else if(cmb4.getSelectedItem().toString()=="Item 002"){
            lblIN4.setText("Double Rod");}
        else if(cmb4.getSelectedItem().toString()=="Item 003"){
            lblIN4.setText("Holdback");}
        else if(cmb4.getSelectedItem().toString()=="Item 004"){
            lblIN4.setText("Clip Ring");}
        else if(cmb4.getSelectedItem().toString()=="Item 005"){
            lblIN4.setText("Brass");}
        else if(cmb4.getSelectedItem().toString()=="Item 006"){
            lblIN4.setText("Flat Bar");}
        else if(cmb4.getSelectedItem().toString()=="Item 007"){
            lblIN4.setText("Single Rail");}
        else if(cmb4.getSelectedItem().toString()=="Item 008"){
            lblIN4.setText("Double Rail");}
        else {
            lblIN4.setText("----");}
                                    
    }//GEN-LAST:event_cmb4ActionPerformed

    private void cmb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb5ActionPerformed

boolean enable = cmb5.getSelectedItem().equals("Item 001") ||cmb5.getSelectedItem().equals("Item 002") || cmb5.getSelectedItem().equals("Item 003") || cmb5.getSelectedItem().equals("Item 004") || cmb5.getSelectedItem().equals("Item 005")|| cmb5.getSelectedItem().equals("Item 005")|| cmb5.getSelectedItem().equals("Item 006")|| cmb5.getSelectedItem().equals("Item 007")|| cmb5.getSelectedItem().equals("Item 008") ;
       txtNOI5.setEnabled(enable);
        txtDes5.setEnabled(enable);

        if(cmb5.getSelectedItem().toString()=="Item 001"){
            lblIN5.setText("Single Rod");}
        else if(cmb5.getSelectedItem().toString()=="Item 002"){
            lblIN5.setText("Double Rod");}
        else if(cmb5.getSelectedItem().toString()=="Item 003"){
            lblIN5.setText("Holdback");}
        else if(cmb5.getSelectedItem().toString()=="Item 004"){
            lblIN5.setText("Clip Ring");}
        else if(cmb5.getSelectedItem().toString()=="Item 005"){
            lblIN5.setText("Brass");}
        else if(cmb5.getSelectedItem().toString()=="Item 006"){
            lblIN5.setText("Flat Bar");}
        else if(cmb5.getSelectedItem().toString()=="Item 007"){
            lblIN5.setText("Single Rail");}
        else if(cmb5.getSelectedItem().toString()=="Item 008"){
            lblIN5.setText("Double Rail");}
        else {
            lblIN5.setText("----");}
                                     
    }//GEN-LAST:event_cmb5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      /*  txtCID.setText("81");
        lblSID.setText("1");
        lblFName.setText("Kamal");
        lblLName.setText("Pieris");
        lblTP.setText("0758686677");
        lblAddress.setText("Galle"); 

        lblFSL.setText("3"); 
        lblIN1.setText("Single Rod");
        lblIN2.setText("Holdback");
        lblIN3.setText("Brass");
        lblIN4.setText("Flat Bar");
        lblIN5.setText("Single Rail"); */
        txtNOI1.setText("2");
        txtNOI2.setText("1");
        txtNOI3.setText("3");
        txtNOI4.setText("2");
        txtNOI5.setText("1");
        txtDes1.setText("Wooden");
        txtDes2.setText("Plastic");
        txtDes3.setText("Silver");
        txtDes4.setText("Wooden");
        txtDes5.setText("Plastic");
        cmb1.setSelectedIndex(1);
        cmb2.setSelectedIndex(3);
        cmb3.setSelectedIndex(5);
        cmb4.setSelectedIndex(4);
        cmb5.setSelectedIndex(2);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        table();
        Reset();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        int g = -1;
        while (g < 0)
        {
            
            String input = JOptionPane.showInputDialog("Please Enter Fixing ID");
            if(input.length() > 0)
            {
                
                 String sql = "delete from fixing_service where fixing_id=? ";
        try  { 
            pst = con.prepareStatement(sql);
            pst.setString(1, input);
            pst.execute();
      
            table();
              Reset();
                         
        }
            
            catch(Exception e){
                    
                    JOptionPane.showMessageDialog(null,"Delete Fail");
                    
                    }
              
                g++;
            }
            else
                JOptionPane.showMessageDialog(null, "Invalid Service ID");
        }
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtCIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCIDKeyReleased
/*        
        if(txtCID.getText().isEmpty()) {
            Reset();
        }
        else {
        try {
               Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
                rs = s.executeQuery("SELECT * FROM customer WHERE ID='"+txtCID.getText()+ "'");
                while (rs.next()) {
                    
                    lblFName.setText(rs.getString("First_Name"));
                    lblLName.setText(rs.getString("Last_Name"));
                    lblTP.setText(rs.getString("Contact_Number"));
                    lblAddress.setText(rs.getString("Address_Line1"));
                    
                }
          } catch (Exception e) {
              
              JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            }
        }
*/
    }//GEN-LAST:event_txtCIDKeyReleased

    private void txtCIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCIDKeyPressed
 if(evt.getKeyCode()==KeyEvent.VK_ENTER) {      
         try {
               Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
                rs = s.executeQuery("SELECT * FROM customer WHERE id='"+txtCID.getText()+ "'");
                while (rs.next()) {
                    
                    lblFName.setText(rs.getString("first_name"));
                    lblLName.setText(rs.getString("last_name"));
                    lblTP.setText(rs.getString("contact_number"));
                    lblAddress.setText(rs.getString("address_line2"));
                    
                }
          } catch (Exception e) {
              
              JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            }
 }
 else {
        lblFName.setText("");
        lblLName.setText("");
        lblTP.setText("");
        lblAddress.setText("");
 }
    }//GEN-LAST:event_txtCIDKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb1;
    private javax.swing.JComboBox<String> cmb2;
    private javax.swing.JComboBox<String> cmb3;
    private javax.swing.JComboBox<String> cmb4;
    private javax.swing.JComboBox<String> cmb5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCDate;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblFSL;
    private javax.swing.JLabel lblIN1;
    private javax.swing.JLabel lblIN2;
    private javax.swing.JLabel lblIN3;
    private javax.swing.JLabel lblIN4;
    private javax.swing.JLabel lblIN5;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblSID;
    private javax.swing.JLabel lblTP;
    private javax.swing.JLabel lblWEDate;
    private javax.swing.JTextField txtCID;
    private javax.swing.JTextField txtDes1;
    private javax.swing.JTextField txtDes2;
    private javax.swing.JTextField txtDes3;
    private javax.swing.JTextField txtDes4;
    private javax.swing.JTextField txtDes5;
    private javax.swing.JTextField txtNOI1;
    private javax.swing.JTextField txtNOI2;
    private javax.swing.JTextField txtNOI3;
    private javax.swing.JTextField txtNOI4;
    private javax.swing.JTextField txtNOI5;
    // End of variables declaration//GEN-END:variables
}
