/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tj.rumesh
 */
public class Customer_warranty_service extends javax.swing.JInternalFrame {
    Connection con= null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    String aa;
    /**
     * Creates new form Customer_warranty_service
     */
    public Customer_warranty_service() {
        initComponents();
        con = DBconnect.connect();
        
        txtab.setEnabled(false);
        txtNOI2.setEnabled(false);
        txtNOI3.setEnabled(false);
        txtNOI4.setEnabled(false);
        txtNOI5.setEnabled(false);
        txtde1.setEnabled(false);
        txtde2.setEnabled(false);
        txtde3.setEnabled(false);
        txtde4.setEnabled(false);
        txtde5.setEnabled(false);
        
        btninvoice.setEnabled(false);
        txtcash.setEnabled(false);
        txtcoin.setEnabled(false);
        btnbalance.setEnabled(false);
        
                      try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM after_service_details");
            while (rs.next()) {

                String ab = rs.getString("service_id");
                int ps = Integer.parseInt(ab);
                int ks = ps+1;
                 String ks1 = String.valueOf(ks);
                 lblSID.setText(ks1);
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Service ID Fail");
            
        }  
                                                                           
         Calendar now = Calendar.getInstance();
		int month = now.get(Calendar.MONTH); 
                int date = now.get(Calendar.DATE); 
                int year = now.get(Calendar.YEAR);
                String Date = year + "-" + month + "-" + date;
                lblCDate.setText(Date);
                
                now.add(Calendar.DATE,7);
		int amonth = now.get(Calendar.MONTH);
                int adate = now.get(Calendar.DATE); 
                int ayear = now.get(Calendar.YEAR);
                String aDate = ayear + "-" + amonth + "-" + adate;
                lblERDate.setText(aDate);
                 table();               
    }

    public Customer_warranty_service(String input) {
        con = DBconnect.connect();
        aa = input;
        String bb = String.valueOf(aa);
        lblFName.setText(bb);
        try {
            
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM fixing_service WHERE customer_id='" + input + "'");
           
            while (rs.next()) {

                lblIDate.setText(rs.getString("dates"));
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            
        }        
        
    }
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblLName = new javax.swing.JLabel();
        lblTP = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblIDate = new javax.swing.JLabel();
        lblCDate = new javax.swing.JLabel();
        lblWL = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        lblSID = new javax.swing.JLabel();
        lblFName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblTItems = new javax.swing.JLabel();
        lblERDate = new javax.swing.JLabel();
        txtwindows = new javax.swing.JTextField();
        txtdoors = new javax.swing.JTextField();
        txtothers = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdes = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        cmb1 = new javax.swing.JComboBox<>();
        cmb2 = new javax.swing.JComboBox<>();
        cmb3 = new javax.swing.JComboBox<>();
        cmb4 = new javax.swing.JComboBox<>();
        cmb5 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        lblIN1 = new javax.swing.JLabel();
        lblIN2 = new javax.swing.JLabel();
        lblIN3 = new javax.swing.JLabel();
        lblIN4 = new javax.swing.JLabel();
        lblIN5 = new javax.swing.JLabel();
        txtNOI1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txtab = new javax.swing.JTextField();
        txtNOI2 = new javax.swing.JTextField();
        txtNOI3 = new javax.swing.JTextField();
        txtNOI4 = new javax.swing.JTextField();
        txtNOI5 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        txtde1 = new javax.swing.JTextField();
        txtde2 = new javax.swing.JTextField();
        txtde3 = new javax.swing.JTextField();
        txtde4 = new javax.swing.JTextField();
        txtde5 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        lblup1 = new javax.swing.JLabel();
        lblup2 = new javax.swing.JLabel();
        lblup3 = new javax.swing.JLabel();
        lblup4 = new javax.swing.JLabel();
        lblup5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        lblTP1 = new javax.swing.JLabel();
        lblTP2 = new javax.swing.JLabel();
        lblTP3 = new javax.swing.JLabel();
        lblTP4 = new javax.swing.JLabel();
        lblTP5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        txtcash = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        lblta = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        lblbal = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        txtcoin = new javax.swing.JTextField();
        btninvoice = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btncalculate = new javax.swing.JButton();
        btnbalance = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        jLabel12.setText("jLabel12");

        setTitle("Warranty Customers Services");
        setEnabled(false);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/itp/11.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(1050, 640));
        setMinimumSize(new java.awt.Dimension(1050, 640));
        setPreferredSize(new java.awt.Dimension(1050, 640));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(292, 214));
        jPanel1.setMinimumSize(new java.awt.Dimension(292, 214));

        jLabel1.setText("Customer ID");

        jLabel2.setText("Customer Name");

        jLabel3.setText("Telephone No  ");

        jLabel4.setText("Address    ");

        jLabel5.setText("Issued Date  ");

        jLabel6.setText("Current Date  ");

        jLabel7.setText("Warranty Left  ");

        lblLName.setEnabled(false);

        lblTP.setEnabled(false);

        lblAddress.setEnabled(false);

        lblIDate.setEnabled(false);

        lblCDate.setEnabled(false);

        lblWL.setEnabled(false);

        jLabel55.setText("Service ID         ");

        lblSID.setEnabled(false);

        lblFName.setToolTipText("please enter customer ID here");
        lblFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblFNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblFNameKeyReleased(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search");
        jButton2.setToolTipText("Do you want to search customer ?");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40)
                                .addComponent(lblLName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(54, 54, 54)
                                    .addComponent(lblWL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(54, 54, 54)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCDate, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                        .addComponent(lblIDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel55))
                                    .addGap(45, 45, 45)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblFName)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton2))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(lblSID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblLName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblIDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblWL))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(407, 105));
        jPanel2.setMinimumSize(new java.awt.Dimension(407, 105));

        jLabel17.setText("Washing ");

        jLabel18.setText("No of Items                  :");

        jLabel19.setText("Windows -");

        jLabel20.setText("Doors -");

        jLabel21.setText("Others -");

        jLabel22.setText("Total Items  ");

        jLabel23.setText("Expect to return Date");

        lblTItems.setEnabled(false);

        lblERDate.setEnabled(false);

        txtwindows.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtwindowsKeyTyped(evt);
            }
        });

        txtdoors.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdoorsKeyTyped(evt);
            }
        });

        txtothers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtothersKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addGap(78, 78, 78)
                                    .addComponent(lblTItems, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addGap(33, 33, 33)
                                    .addComponent(lblERDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtwindows, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdoors, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtothers, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(txtwindows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdoors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtothers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lblTItems))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblERDate))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setMaximumSize(new java.awt.Dimension(308, 43));
        jPanel5.setMinimumSize(new java.awt.Dimension(308, 43));

        jLabel26.setText("Others");

        jLabel27.setText("Description                   :");

        txtdes.setColumns(20);
        txtdes.setRows(5);
        jScrollPane1.setViewportView(txtdes);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setMaximumSize(new java.awt.Dimension(99, 170));
        jPanel4.setMinimumSize(new java.awt.Dimension(99, 170));

        jLabel29.setText("Item Id");

        cmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1ActionPerformed(evt);
            }
        });

        cmb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb2ActionPerformed(evt);
            }
        });

        cmb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb3ActionPerformed(evt);
            }
        });

        cmb4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb4ActionPerformed(evt);
            }
        });

        cmb5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmb1, 0, 75, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel29))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmb3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmb4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmb2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmb5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(cmb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(cmb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(cmb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(cmb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setMaximumSize(new java.awt.Dimension(116, 129));
        jPanel6.setMinimumSize(new java.awt.Dimension(116, 129));

        jLabel30.setText("Item Name");

        lblIN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN1.setEnabled(false);

        lblIN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN2.setEnabled(false);

        lblIN3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN3.setEnabled(false);

        lblIN4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN4.setEnabled(false);

        lblIN5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN5.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel30)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIN3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIN2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIN1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIN4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIN5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIN1)
                .addGap(18, 18, 18)
                .addComponent(lblIN2)
                .addGap(18, 18, 18)
                .addComponent(lblIN3)
                .addGap(18, 18, 18)
                .addComponent(lblIN4)
                .addGap(18, 18, 18)
                .addComponent(lblIN5)
                .addGap(17, 17, 17))
        );

        txtNOI1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNOI1.setMaximumSize(new java.awt.Dimension(106, 170));
        txtNOI1.setMinimumSize(new java.awt.Dimension(106, 170));

        jLabel31.setText("No of Item used");

        txtab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtabKeyTyped(evt);
            }
        });

        txtNOI2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNOI2KeyTyped(evt);
            }
        });

        txtNOI3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNOI3KeyTyped(evt);
            }
        });

        txtNOI4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNOI4KeyTyped(evt);
            }
        });

        txtNOI5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNOI5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout txtNOI1Layout = new javax.swing.GroupLayout(txtNOI1);
        txtNOI1.setLayout(txtNOI1Layout);
        txtNOI1Layout.setHorizontalGroup(
            txtNOI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtNOI1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtNOI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtab)
                    .addComponent(txtNOI2)
                    .addComponent(txtNOI3)
                    .addComponent(txtNOI4)
                    .addComponent(txtNOI5))
                .addGap(15, 15, 15))
        );
        txtNOI1Layout.setVerticalGroup(
            txtNOI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtNOI1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNOI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNOI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNOI4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNOI5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setMaximumSize(new java.awt.Dimension(104, 170));
        jPanel8.setMinimumSize(new java.awt.Dimension(104, 170));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Description");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtde1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtde2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtde3)
                    .addComponent(txtde4)
                    .addComponent(txtde5))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtde5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setMaximumSize(new java.awt.Dimension(99, 129));
        jPanel9.setMinimumSize(new java.awt.Dimension(99, 129));

        jLabel33.setText("Unit Price  (Rs.)");

        lblup1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblup1.setEnabled(false);

        lblup2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblup2.setEnabled(false);

        lblup3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblup3.setEnabled(false);

        lblup4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblup4.setEnabled(false);

        lblup5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblup5.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblup1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblup2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblup3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblup4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblup5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblup1)
                .addGap(18, 18, 18)
                .addComponent(lblup2)
                .addGap(18, 18, 18)
                .addComponent(lblup3)
                .addGap(18, 18, 18)
                .addComponent(lblup4)
                .addGap(18, 18, 18)
                .addComponent(lblup5)
                .addGap(17, 17, 17))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setMaximumSize(new java.awt.Dimension(104, 132));
        jPanel10.setMinimumSize(new java.awt.Dimension(104, 132));

        jLabel34.setText("Total Price  (Rs.)");

        lblTP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTP1.setEnabled(false);

        lblTP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTP2.setEnabled(false);

        lblTP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTP3.setEnabled(false);

        lblTP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTP4.setEnabled(false);

        lblTP5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTP5.setEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTP4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTP5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTP1)
                .addGap(18, 18, 18)
                .addComponent(lblTP2)
                .addGap(18, 18, 18)
                .addComponent(lblTP3)
                .addGap(18, 18, 18)
                .addComponent(lblTP4)
                .addGap(18, 18, 18)
                .addComponent(lblTP5)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtNOI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNOI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setMaximumSize(new java.awt.Dimension(660, 46));
        jPanel11.setMinimumSize(new java.awt.Dimension(660, 46));

        jLabel50.setText("Total Amount (Rs.)  :");

        txtcash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcashKeyTyped(evt);
            }
        });

        jLabel51.setText("Cash Payment  (Rs.)  :");

        jLabel53.setText("Balance  (Rs.)       :");

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel57.setText(".");

        txtcoin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcoinKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcash, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcoin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblbal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(txtcash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51)
                    .addComponent(lblta)
                    .addComponent(jLabel53)
                    .addComponent(lblbal)
                    .addComponent(jLabel57)
                    .addComponent(txtcoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btninvoice.setBackground(new java.awt.Color(0, 51, 51));
        btninvoice.setForeground(new java.awt.Color(255, 255, 255));
        btninvoice.setText("Report");
        btninvoice.setToolTipText("Do you want to send report or bill ?");
        btninvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninvoiceActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.setToolTipText("Reset everythings");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 51, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Refresh");
        jButton4.setToolTipText("Do you want to refresh the database ?");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Service ID", "Customer ID", "Date", "Item No", "Qty", "Description", "Item No", "Qty", "Description", "Item No", "Qty", "Description", "Item No", "Qty", "Description", "Item No", "Qty", "Description", "Wash Qty", "Wash Items", "Total", "Pay", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable1);

        btncalculate.setBackground(new java.awt.Color(0, 51, 51));
        btncalculate.setForeground(new java.awt.Color(255, 255, 255));
        btncalculate.setText("Calculate");
        btncalculate.setToolTipText("Do you want to calculate the cost and charges ?");
        btncalculate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculateActionPerformed(evt);
            }
        });

        btnbalance.setBackground(new java.awt.Color(0, 51, 51));
        btnbalance.setForeground(new java.awt.Color(255, 255, 255));
        btnbalance.setText("Balance");
        btnbalance.setToolTipText("Do you want to check the balance ?");
        btnbalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbalanceActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 255));
        jButton1.setText("Demo");
        jButton1.setToolTipText("Demo to test");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btninvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btninvoice)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(btncalculate)
                            .addComponent(btnbalance)
                            .addComponent(jButton1)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                .addGap(123, 123, 123))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Reset() {
   

        lblFName.setText("");
        lblLName.setText("");
        lblTP.setText("");
        lblAddress.setText("");
        txtwindows.setText("");
        txtdoors.setText("");
        txtothers.setText("");
        lblWL.setText("");
       
        lblTItems.setText("");
        txtdes.setText("");
        lblIN1.setText("");
        lblIN2.setText("");
        lblIN3.setText("");
        lblIN4.setText("");
        lblIN5.setText("");
        txtab.setText("");
        txtNOI2.setText("");
        txtNOI3.setText("");
        txtNOI4.setText("");
        txtNOI5.setText("");
        txtde1.setText("");
        txtde2.setText("");
        txtde3.setText("");
        txtde4.setText("");
        txtde5.setText("");
        lblup1.setText("");
        lblup2.setText("");
        lblup3.setText("");
        lblup4.setText("");
        lblup5.setText("");
        lblTP1.setText("");
        lblTP2.setText("");
        lblTP3.setText("");
        lblTP4.setText("");
        lblTP5.setText("");
        lblta.setText("");
        txtcash.setText("");
        lblbal.setText("");
        cmb1.setSelectedIndex(0);
        cmb2.setSelectedIndex(0);
        cmb3.setSelectedIndex(0);
        cmb4.setSelectedIndex(0);
        cmb5.setSelectedIndex(0);
    }
    
    
    public void table() {

        DefaultTableModel dtf = (DefaultTableModel) jTable1.getModel();
        dtf.setRowCount(0);

        try {
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
            
            rs=s.executeQuery("SELECT * FROM after_service_details");

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("service_id"));
                v.add(rs.getString("customer_id"));
             
                v.add(rs.getString("dates"));
                v.add(rs.getString("item"));
                v.add(rs.getString("use_qty_1"));
                v.add(rs.getString("description_1"));
                v.add(rs.getString("item_no_2"));
                v.add(rs.getString("use_qty_2"));
                v.add(rs.getString("description_2"));
                v.add(rs.getString("item_no_3"));
                v.add(rs.getString("use_qty_3"));
                v.add(rs.getString("description_3"));
                v.add(rs.getString("item_no_4"));
                v.add(rs.getString("use_qty_4"));
                v.add(rs.getString("description_4"));
                v.add(rs.getString("item_no_5"));
                v.add(rs.getString("use_qty_5"));
                v.add(rs.getString("description_5"));
                v.add(rs.getString("washing_qty"));
                v.add(rs.getString("no_of_items"));
             
                v.add(rs.getString("total_charge"));
                v.add(rs.getString("cash_payment"));
                v.add(rs.getString("balance"));
             
                            
                dtf.addRow(v);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Table load kk Fail");
        }
    }
    
    
    private void txtwindowsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtwindowsKeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtwindowsKeyTyped

    private void txtdoorsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdoorsKeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtdoorsKeyTyped

    private void txtothersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtothersKeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtothersKeyTyped

    private void txtabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtabKeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtabKeyTyped

    private void txtNOI2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNOI2KeyTyped
       char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtNOI2KeyTyped

    private void txtNOI3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNOI3KeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtNOI3KeyTyped

    private void txtNOI4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNOI4KeyTyped
       char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtNOI4KeyTyped

    private void txtNOI5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNOI5KeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtNOI5KeyTyped

    private void txtcashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcashKeyTyped
       char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtcashKeyTyped

    private void txtcoinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcoinKeyTyped
       char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtcoinKeyTyped

    private void btninvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninvoiceActionPerformed
        if (lblFName.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please Enter Customer ID");
        }
     
        else if (lblLName.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select valid customer");    
        }
        
        else {
        String SID = lblSID.getText();
        String fname = lblFName.getText();
        String lname = lblLName.getText();
        String tp = lblTP.getText();
        String issue = lblIDate.getText();
        String date = lblCDate.getText();
        String address = lblAddress.getText();
        String war = lblWL.getText();
        
        String win = txtwindows.getText();
        String door = txtdoors.getText();
        String other = txtothers.getText();
        String TI = lblTItems.getText();
        String ER = lblERDate.getText();
        
        String Des = txtdes.getText();
   
        String in1 = lblIN1.getText();
        String in2 = lblIN2.getText();
        String in3 = lblIN3.getText();
        String in4 = lblIN4.getText();
        String in5 = lblIN5.getText();
        
        String no1 = txtab.getText();
        String no2 = txtNOI2.getText();
        String no3 = txtNOI3.getText();
        String no4 = txtNOI4.getText();
        String no5 = txtNOI5.getText();
        String de1 = txtde1.getText();
        String de2 = txtde2.getText();
        String de3 = txtde3.getText();
        String de4 = txtde4.getText();
        String de5 = txtde5.getText();
        String up1 = lblup1.getText();
        String up2 = lblup2.getText();
        String up3 = lblup3.getText();
        String up4 = lblup4.getText();
        String up5 = lblup5.getText();
        String tp1 = lblTP1.getText();
        String tp2 = lblTP2.getText();
        String tp3 = lblTP3.getText();
        String tp4 = lblTP4.getText();
        String tp5 = lblTP5.getText();
       
        String ta = lblta.getText();
        String ca = txtcash.getText();
        String bal = lblbal.getText();
        String ccmb1 = cmb1.getSelectedItem().toString();
        String ccmb2 = cmb2.getSelectedItem().toString();
        String ccmb3 = cmb3.getSelectedItem().toString();
        String ccmb4 = cmb4.getSelectedItem().toString();
        String ccmb5 = cmb5.getSelectedItem().toString();
    
        Warranty_Report wr = new Warranty_Report(SID,fname,lname,tp,issue,address,war,date,win,door,other,TI,ER,Des,in1,in2,in3,in4,in5,no1,no2,no3,no4,no5,de1,de2,de3,de4,de5,up1,up2,up3,up4,up5,tp1,tp2,tp3,tp4,tp5,ta,ca,bal,ccmb1,ccmb2,ccmb3,ccmb4,ccmb5);
        wr.setVisible(true);
      
        }
    }//GEN-LAST:event_btninvoiceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Reset();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculateActionPerformed
        
        if(lblFName.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Select Customer");
        }
        else {  
                      
        btnbalance.setEnabled(true);
        txtcash.setEnabled(true);
        txtcoin.setEnabled(true);
        

        if(txtwindows.getText().isEmpty()){
            txtwindows.setText("0");
        }
        
        if(txtdoors.getText().isEmpty()) {
            txtdoors.setText("0");
        }
        
        if(txtothers.getText().isEmpty()) {
            txtothers.setText("0");
        }
        
        if(txtab.getText().isEmpty()){
            txtab.setText("0");
        }
        
        if(txtNOI2.getText().isEmpty()){
            txtNOI2.setText("0");
        }
        
        if(txtNOI3.getText().isEmpty()){
            txtNOI3.setText("0");
        }
        
        if(txtNOI4.getText().isEmpty()){
            txtNOI4.setText("0");
        }
        
            if(lblup1.getText().isEmpty()){
            lblup1.setText("0");
        }
                
            if(lblup2.getText().isEmpty()){
            lblup2.setText("0");
        }
                        
            if(lblup3.getText().isEmpty()){
            lblup3.setText("0");
        }
            if(lblup4.getText().isEmpty()){
            lblup4.setText("0");
        }
                                        
            if(lblup5.getText().isEmpty()){
            lblup5.setText("0");
        }
                                
        if(txtNOI5.getText().isEmpty()){
            txtNOI5.setText("0");
        }
        
        String windows = txtwindows.getText();
        String doors = txtdoors.getText();
        String others = txtothers.getText();
        
        int w = Integer.parseInt(windows);
        int d = Integer.parseInt(doors);
        int o = Integer.parseInt(others);
        
        int total = w + d + o ;
        
        String count = String.valueOf(total);
        
        lblTItems.setText(count);
        
        String I1 = txtab.getText();
        String I2 = txtNOI2.getText();
        String I3 = txtNOI3.getText();
        String I4 = txtNOI4.getText();
        String I5 = txtNOI5.getText();
        
        double I11 = Double.parseDouble(I1);
        double I12 = Double.parseDouble(I2);
        double I13 = Double.parseDouble(I3);
        double I14 = Double.parseDouble(I4);
        double I15 = Double.parseDouble(I5);
        
        String UP1 = lblup1.getText();
        String UP2 = lblup2.getText();
        String UP3 = lblup3.getText();
        String UP4 = lblup4.getText();
        String UP5 = lblup5.getText();
        
        double UP11 = Double.parseDouble(UP1);
        double UP12 = Double.parseDouble(UP2);
        double UP13 = Double.parseDouble(UP3);
        double UP14 = Double.parseDouble(UP4);
        double UP15 = Double.parseDouble(UP5);
        
        double UI1 = I11 * UP11 ;
        double UI2 = I12 * UP12 ;
        double UI3 = I13 * UP13 ;
        double UI4 = I14 * UP14 ;
        double UI5 = I15 * UP15 ;
        
        String UII1 = String.valueOf(UI1);
        String UII2 = String.valueOf(UI2);
        String UII3 = String.valueOf(UI3);
        String UII4 = String.valueOf(UI4);
        String UII5 = String.valueOf(UI5);
        
        lblTP1.setText(UII1);
        lblTP2.setText(UII2);
        lblTP3.setText(UII3);
        lblTP4.setText(UII4);
        lblTP5.setText(UII5);
        double amount = UI1 + UI2 + UI3 + UI4 + UI5 ;
        String totalamount = String.valueOf(amount);
        lblta.setText(totalamount);
}
    }//GEN-LAST:event_btncalculateActionPerformed

    private void btnbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbalanceActionPerformed

        if (txtcash.getText().isEmpty()) {
           JOptionPane.showMessageDialog(null, "Please Enter payment value");
        }
        
        if (txtcoin.getText().isEmpty()){
            txtcoin.setText("00");
        }
        
        
        else {
        
        btninvoice.setEnabled(true);
            
        
        String TTp1 = lblTP1.getText();
        String TTp2 = lblTP2.getText();
        String TTp3 = lblTP3.getText();
        String TTp4 = lblTP4.getText();
        String TTp5 = lblTP5.getText();
        
        double TTc1 = Double.parseDouble(TTp1);
        double TTc2 = Double.parseDouble(TTp2);
        double TTc3 = Double.parseDouble(TTp3);
        double TTc4 = Double.parseDouble(TTp4);
        double TTc5 = Double.parseDouble(TTp5);
        
        double amount = TTc1 + TTc2 + TTc3 + TTc4 + TTc5 ;
        String totalamount = String.valueOf(amount);
        lblta.setText(totalamount);
        
        String csh = txtcash.getText();
        String coin = txtcoin.getText();
        
        double HH1 = Double.parseDouble(csh);
        double HH2 = Double.parseDouble(coin);
        
        double HH3 = HH1 + (HH2 / 100.0) ;
        
        double bal1 = HH3 - amount ;
        
        String balance1 = String.valueOf(bal1);
        lblbal.setText(balance1);
        }
    }//GEN-LAST:event_btnbalanceActionPerformed

    private void cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1ActionPerformed


  boolean enable = cmb1.getSelectedItem().equals("Item 001") ||cmb1.getSelectedItem().equals("Item 002") || cmb1.getSelectedItem().equals("Item 003") || cmb1.getSelectedItem().equals("Item 004") || cmb1.getSelectedItem().equals("Item 005")|| cmb1.getSelectedItem().equals("Item 005")|| cmb1.getSelectedItem().equals("Item 006")|| cmb1.getSelectedItem().equals("Item 007")|| cmb1.getSelectedItem().equals("Item 008") ;
       txtab.setEnabled(enable);
        txtde1.setEnabled(enable);
 

        try {
          
            
            Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
            rs=s.executeQuery("SELECT * FROM stock_details WHERE item_no='"+ cmb1.getSelectedItem().toString() + "'");
            while (rs.next()) {

                lblIN1.setText(rs.getString("item_name"));
                lblup1.setText(rs.getString("selling_price"));
               
         }
            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cmb1ActionPerformed

    private void cmb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb2ActionPerformed

boolean enable = cmb2.getSelectedItem().equals("Item 001") ||cmb2.getSelectedItem().equals("Item 002") || cmb2.getSelectedItem().equals("Item 003") || cmb2.getSelectedItem().equals("Item 004") || cmb2.getSelectedItem().equals("Item 005")|| cmb2.getSelectedItem().equals("Item 005")|| cmb2.getSelectedItem().equals("Item 006")|| cmb2.getSelectedItem().equals("Item 007")|| cmb2.getSelectedItem().equals("Item 008") ;
       txtNOI2.setEnabled(enable);
        txtde2.setEnabled(enable);

        try {
          
            
            Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
            rs=s.executeQuery("SELECT * FROM stock_details WHERE item_no='"+ cmb2.getSelectedItem().toString() + "'");
            while (rs.next()) {

                lblIN2.setText(rs.getString("item_name"));
                lblup2.setText(rs.getString("selling_price"));
               
         }
            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cmb2ActionPerformed

    private void cmb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb3ActionPerformed

boolean enable = cmb3.getSelectedItem().equals("Item 001") ||cmb3.getSelectedItem().equals("Item 002") || cmb3.getSelectedItem().equals("Item 003") || cmb3.getSelectedItem().equals("Item 004") || cmb3.getSelectedItem().equals("Item 005")|| cmb3.getSelectedItem().equals("Item 005")|| cmb3.getSelectedItem().equals("Item 006")|| cmb3.getSelectedItem().equals("Item 007")|| cmb3.getSelectedItem().equals("Item 008") ;
       txtNOI3.setEnabled(enable);
        txtde3.setEnabled(enable);

        try {
          
            
            Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
            rs=s.executeQuery("SELECT * FROM stock_details WHERE item_no='"+ cmb3.getSelectedItem().toString() + "'");
            while (rs.next()) {

                lblIN3.setText(rs.getString("item_name"));
                lblup3.setText(rs.getString("selling_price"));
               
         }
            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cmb3ActionPerformed

    private void cmb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb4ActionPerformed

boolean enable = cmb4.getSelectedItem().equals("Item 001") ||cmb4.getSelectedItem().equals("Item 002") || cmb4.getSelectedItem().equals("Item 003") || cmb4.getSelectedItem().equals("Item 004") || cmb4.getSelectedItem().equals("Item 005")|| cmb4.getSelectedItem().equals("Item 005")|| cmb4.getSelectedItem().equals("Item 006")|| cmb4.getSelectedItem().equals("Item 007")|| cmb4.getSelectedItem().equals("Item 008") ;
       txtNOI4.setEnabled(enable);
        txtde4.setEnabled(enable);
        try {
          
            
            Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
            rs=s.executeQuery("SELECT * FROM stock_details WHERE item_no='"+ cmb4.getSelectedItem().toString() + "'");
            while (rs.next()) {

                lblIN4.setText(rs.getString("item_name"));
                lblup4.setText(rs.getString("selling_price"));
               
         }
            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cmb4ActionPerformed

    private void cmb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb5ActionPerformed
       
        boolean enable = cmb5.getSelectedItem().equals("Item 001") ||cmb5.getSelectedItem().equals("Item 002") || cmb5.getSelectedItem().equals("Item 003") || cmb5.getSelectedItem().equals("Item 004") || cmb5.getSelectedItem().equals("Item 005")|| cmb5.getSelectedItem().equals("Item 005")|| cmb5.getSelectedItem().equals("Item 006")|| cmb5.getSelectedItem().equals("Item 007")|| cmb5.getSelectedItem().equals("Item 008") ;
       txtNOI5.setEnabled(enable);
        txtde5.setEnabled(enable);
        try {
          
            
            Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
            rs=s.executeQuery("SELECT * FROM stock_details WHERE item_no='"+ cmb5.getSelectedItem().toString() + "'");
            while (rs.next()) {

                lblIN5.setText(rs.getString("item_name"));
                lblup5.setText(rs.getString("selling_price"));
               
         }
            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cmb5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
      /*  lblSID.setText("1");
        lblFName.setText("17");
        lblLName.setText("Perera");
        lblTP.setText("0727876764");
        lblAddress.setText("Seeduwa"); */

        txtwindows.setText("6");
        txtdoors.setText("4");
        txtothers.setText("5");
      /*  lblWL.setText("0");
        lblIDate.setText("07-26-2016");

        txtdes.setText("Has Customer Faults");
        lblIN1.setText("Single Rod");
        lblIN2.setText("Double Rod");
        lblIN3.setText("Double Rail");
        lblIN4.setText("Single Rail");
        lblIN5.setText("Clip Ring"); */
        txtab.setText("2");
        txtNOI2.setText("1");
        txtNOI3.setText("3");
        txtNOI4.setText("1");
        txtNOI5.setText("3");
        txtde1.setText("Silver");
        txtde2.setText("Wooden");
        txtde3.setText("Wooden");
        txtde4.setText("Silver");
        txtde5.setText("Aluminium");
        lblup1.setText("120.00");
        lblup2.setText("115.50");
        lblup3.setText("100.00");
        lblup4.setText("65.50");
        lblup5.setText("50.00");

        cmb1.setSelectedIndex(1);
        cmb2.setSelectedIndex(2);
        cmb3.setSelectedIndex(3);
        cmb4.setSelectedIndex(5);
        cmb5.setSelectedIndex(4);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        table();
        Reset();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (lblFName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Customer ID");
        }
        
        else {
         try {
            
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM fixing_service WHERE customer_id='" + lblFName.getText() + "'");
           
            while (rs.next()) {

                lblIDate.setText(rs.getString("dates"));
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            
        }        
    
        
         try {
            
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM customer where id='" + lblFName.getText() + "'");
           
            while (rs.next()) {

                lblLName.setText(rs.getString("last_name"));
                lblTP.setText(rs.getString("contact_number"));
                lblAddress.setText(rs.getString("address_line2"));
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            
        }        
    
         try {
            
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM check_warranty WHERE customer_id='" + lblFName.getText() + "'");
           
            while (rs.next()) {

                lblWL.setText(rs.getString("warr_left"));
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            
        }        
     
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
       if (lblFName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Customer ID");
        }
        
        else {
         try {
            
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM fixing_service WHERE customer_id='" + lblFName.getText() + "'");
           
            while (rs.next()) {

                lblIDate.setText(rs.getString("dates"));
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            
        }        
    
        
         try {
            
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM customer where id='" + lblFName.getText() + "'");
           
            while (rs.next()) {

                lblLName.setText(rs.getString("last_name"));
                lblTP.setText(rs.getString("contact_number"));
                lblAddress.setText(rs.getString("address_line2"));
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            
        }        
    
         try {
            
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM check_warranty WHERE customer_id='" + lblFName.getText() + "'");
           
            while (rs.next()) {

                lblWL.setText(rs.getString("warr_left"));
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            
        }        
     
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void lblFNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblFNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFNameKeyReleased

    private void lblFNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblFNameKeyPressed
                
         if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
        
        try {
            
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM fixing_service WHERE customer_id='" + lblFName.getText() + "'");
           
            while (rs.next()) {

                lblIDate.setText(rs.getString("dates"));
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            
        }        
    
        
         try {
            
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM customer where id='" + lblFName.getText() + "'");
           
            while (rs.next()) {

                lblLName.setText(rs.getString("last_name"));
                lblTP.setText(rs.getString("contact_number"));
                lblAddress.setText(rs.getString("address_line2"));
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            
        }        
    
         try {
            
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM check_warranty WHERE customer_id='" + lblFName.getText() + "'");
           
            while (rs.next()) {

                lblWL.setText(rs.getString("warr_left"));
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
        }
        }   
         else {              
        lblLName.setText("");
        lblTP.setText("");
        lblAddress.setText("");
        lblIDate.setText("");
        lblWL.setText("");
         }
    }//GEN-LAST:event_lblFNameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbalance;
    private javax.swing.JButton btncalculate;
    private javax.swing.JButton btninvoice;
    private javax.swing.JComboBox<String> cmb1;
    private javax.swing.JComboBox<String> cmb2;
    private javax.swing.JComboBox<String> cmb3;
    private javax.swing.JComboBox<String> cmb4;
    private javax.swing.JComboBox<String> cmb5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCDate;
    private javax.swing.JLabel lblERDate;
    private javax.swing.JTextField lblFName;
    private javax.swing.JLabel lblIDate;
    private javax.swing.JLabel lblIN1;
    private javax.swing.JLabel lblIN2;
    private javax.swing.JLabel lblIN3;
    private javax.swing.JLabel lblIN4;
    private javax.swing.JLabel lblIN5;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblSID;
    private javax.swing.JLabel lblTItems;
    private javax.swing.JLabel lblTP;
    private javax.swing.JLabel lblTP1;
    private javax.swing.JLabel lblTP2;
    private javax.swing.JLabel lblTP3;
    private javax.swing.JLabel lblTP4;
    private javax.swing.JLabel lblTP5;
    private javax.swing.JLabel lblWL;
    private javax.swing.JLabel lblbal;
    private javax.swing.JLabel lblta;
    private javax.swing.JLabel lblup1;
    private javax.swing.JLabel lblup2;
    private javax.swing.JLabel lblup3;
    private javax.swing.JLabel lblup4;
    private javax.swing.JLabel lblup5;
    private javax.swing.JPanel txtNOI1;
    private javax.swing.JTextField txtNOI2;
    private javax.swing.JTextField txtNOI3;
    private javax.swing.JTextField txtNOI4;
    private javax.swing.JTextField txtNOI5;
    private javax.swing.JTextField txtab;
    private javax.swing.JTextField txtcash;
    private javax.swing.JTextField txtcoin;
    private javax.swing.JTextField txtde1;
    private javax.swing.JTextField txtde2;
    private javax.swing.JTextField txtde3;
    private javax.swing.JTextField txtde4;
    private javax.swing.JTextField txtde5;
    private javax.swing.JTextArea txtdes;
    private javax.swing.JTextField txtdoors;
    private javax.swing.JTextField txtothers;
    private javax.swing.JTextField txtwindows;
    // End of variables declaration//GEN-END:variables
}
