/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author tj.rumesh
 */
public class Customer_Services extends javax.swing.JInternalFrame {
    Connection con= null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    PreparedStatement std = null;
    /**
     * Creates new form Customer_Services
     */
    public Customer_Services() {
        initComponents();
        con = DBconnect.connect();
        customer_warranty_service1.setVisible(false);
        customer_Non_Warranty_Service2.setVisible(false);
    }
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        customer_Before_Service2 = new itp.Customer_Before_Service();
        jPanel2 = new javax.swing.JPanel();
        customer_Service_fix1 = new itp.Customer_Service_fix();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        customer_warranty_service1 = new itp.Customer_warranty_service();
        jPanel5 = new javax.swing.JPanel();
        customer_Non_Warranty_Service2 = new itp.Customer_Non_Warranty_Service();

        setTitle("Curtains Services");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/itp/bs.png"))); // NOI18N

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        customer_Before_Service2.setVisible(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(customer_Before_Service2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(customer_Before_Service2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Before Customer Services", jPanel1);

        customer_Service_fix1.setVisible(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(customer_Service_fix1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 126, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(customer_Service_fix1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fixing Services", jPanel2);

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        customer_warranty_service1.setVisible(true);
        customer_warranty_service1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                customer_warranty_service1InternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        customer_warranty_service1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_warranty_service1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                customer_warranty_service1MousePressed(evt);
            }
        });
        customer_warranty_service1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                customer_warranty_service1AncestorRemoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(customer_warranty_service1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 121, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(customer_warranty_service1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Warranty Services", jPanel4);

        customer_Non_Warranty_Service2.setVisible(true);
        customer_Non_Warranty_Service2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                customer_Non_Warranty_Service2AncestorRemoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(customer_Non_Warranty_Service2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 121, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(customer_Non_Warranty_Service2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Non-Warranty Saervices", jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("After Customer Services", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
            
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    public void Reset() {
        customer_warranty_service1.setVisible(false);
        customer_Non_Warranty_Service2.setVisible(false);
    }
    
    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
       
    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        Reset();
        
        Calendar now = Calendar.getInstance();
		int month = now.get(Calendar.MONTH); 
                int date = now.get(Calendar.DATE); 
                int year = now.get(Calendar.YEAR);
                String Date1 = year + "-" + month + "-" + date;
                Date dd1 = Date.valueOf(Date1);
                
        int g = -1;
        while (g < 0)
        {
            
            String input = JOptionPane.showInputDialog("Please Enter Customer ID");
            if(input.length() > 0)
            {
                
                 String sql = "SELECT * from check_warranty where customer_id=? OR nic=?";
        try  { 
            pst = con.prepareStatement(sql);
            pst.setString(1, input);
            pst.setString(2, input);
            pst.execute();
   
         try {   
             String sql2 = "UPDATE check_warranty SET curr_date='"+dd1+"' WHERE customer_id='"+input+"' OR nic='"+input+"'";

        std = con.prepareStatement(sql2);
        std.execute();
    
    
        } catch (Exception e)
        {
      
         }

            try {
            
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM check_warranty WHERE customer_id='" + input + "' OR nic='"+input+"'");

            while (rs.next()) {
                String cusid = rs.getString("customer_id");
                String wl = rs.getString("warr_left");
                Date d1 = rs.getDate("issue_date"); 
                Date d2 = rs.getDate("curr_date"); 
                
                long diff = d2.getTime() - d1.getTime();
                long difference = (diff / (1000 * 60 * 60 * 24));
               
                int abc = Integer.parseInt(wl);
                
                if(abc != 0 && difference < 366 ) {
                    JOptionPane.showMessageDialog(null, "Warranty Customer, Customer ID : " + cusid);
                    customer_warranty_service1.setVisible(true);
                    customer_Non_Warranty_Service2.setVisible(false);
                }
                else if (abc == 0 || difference >= 366 ) {
                    JOptionPane.showMessageDialog(null, "Non-Warranty Customer, Customer ID : " + cusid);
                    customer_Non_Warranty_Service2.setVisible(true);
                    customer_warranty_service1.setVisible(false);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Invalid Cuctomer ID");
                    customer_warranty_service1.setVisible(false);
                    customer_Non_Warranty_Service2.setVisible(false);
                }
                              
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ID");           
        }        
        }
            
            catch(Exception e){
                    
                    JOptionPane.showMessageDialog(null,"Cannot find Customer");
                    
                    }       
                g++;
            }
            else
                JOptionPane.showMessageDialog(null, "Invalid Customer ID");
        }       
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void customer_warranty_service1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_warranty_service1MouseClicked
        
    }//GEN-LAST:event_customer_warranty_service1MouseClicked

    private void customer_warranty_service1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_warranty_service1MousePressed
        
    }//GEN-LAST:event_customer_warranty_service1MousePressed

    private void customer_Non_Warranty_Service2AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_customer_Non_Warranty_Service2AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_Non_Warranty_Service2AncestorRemoved

    private void customer_warranty_service1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_customer_warranty_service1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_warranty_service1AncestorRemoved

    private void customer_warranty_service1InternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_customer_warranty_service1InternalFrameDeactivated

    }//GEN-LAST:event_customer_warranty_service1InternalFrameDeactivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itp.Customer_Before_Service customer_Before_Service2;
    private itp.Customer_Non_Warranty_Service customer_Non_Warranty_Service2;
    private itp.Customer_Service_fix customer_Service_fix1;
    private itp.Customer_warranty_service customer_warranty_service1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
