/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tj.rumesh
 */
public class Service_Group extends javax.swing.JInternalFrame {
    Connection con= null;
    ResultSet rs=null;
    ResultSet rs1=null;
    ResultSet rs2=null;
    PreparedStatement pst=null;
 
    /**
     * Creates new form Service_Group
     */
    public Service_Group() {
        initComponents();
        con = DBconnect.connect();
        
                    incre();
                    jButton5.setEnabled(false);
                    jButton6.setEnabled(false);
                    jButton9.setEnabled(false);
        
         table();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        setTitle("Company Service Groups");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/itp/se.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(1050, 640));
        setMinimumSize(new java.awt.Dimension(1050, 640));
        setPreferredSize(new java.awt.Dimension(1050, 640));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(290, 180));
        jPanel1.setMinimumSize(new java.awt.Dimension(290, 180));

        jLabel2.setText("Name");

        jLabel1.setText("Employee No");

        jLabel3.setText("Telephone No");

        jLabel4.setText("NIC number");

        jLabel5.setText("Address");

        jLabel6.setText("Service Group Leader");

        jTextField1.setToolTipText("Please enter leader's employee ID here");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel7.setEnabled(false);

        jLabel8.setEnabled(false);

        jLabel9.setEnabled(false);

        jLabel10.setEnabled(false);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.setToolTipText("search leader's employee ID");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel34.setForeground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel34))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(273, 171));
        jPanel2.setMinimumSize(new java.awt.Dimension(273, 171));

        jLabel11.setText("Member 01");

        jLabel12.setText("Employee No");

        jLabel13.setText("Name");

        jLabel14.setText("NIC number");

        jLabel15.setText("Telephone No");

        jLabel16.setText("Address");

        jTextField2.setToolTipText("Please enter member's employee ID here");
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jLabel17.setEnabled(false);

        jLabel18.setEnabled(false);

        jLabel19.setEnabled(false);

        jLabel20.setEnabled(false);

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search");
        jButton2.setToolTipText("search member employee ID");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel35.setForeground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 241, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35))))
            .addComponent(jLabel11)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel35))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMaximumSize(new java.awt.Dimension(342, 208));
        jPanel3.setMinimumSize(new java.awt.Dimension(342, 208));

        jLabel22.setText("Employee No");

        jLabel21.setText("Name");

        jLabel23.setText("NIC number");

        jLabel24.setText("Telephone No");

        jLabel25.setText("Address");

        jLabel26.setText("Member 02");

        jTextField3.setToolTipText("Please enter member's employee ID here");
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jLabel27.setEnabled(false);

        jLabel28.setEnabled(false);

        jLabel29.setEnabled(false);

        jLabel30.setEnabled(false);

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Search");
        jButton3.setToolTipText("search member's employee ID ");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel36.setForeground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel26)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel26)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel36))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel30)))
                            .addComponent(jLabel29)))
                    .addComponent(jLabel27))
                .addGap(35, 35, 35))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Group ID", "Leader`s Emp No", "Leader`s Name", "Leader`s TP", "Leader`s Address", "Member 01 Emp No", "Member 01 Name", "Member 01 TP", "Member 01 Address", "Member 02 Emp No", "Member 02 Name", "Member 02 TP", "Member 02 Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setMinimumSize(new java.awt.Dimension(975, 320));
        jTable1.setName(""); // NOI18N
        jTable1.setPreferredSize(new java.awt.Dimension(1400, 320));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Save");
        jButton4.setToolTipText("Do you want to save the created groups ?");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Delete");
        jButton6.setToolTipText("Do you want to delete service groups ?");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Clear");
        jButton7.setToolTipText("Reset everythings");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Close");
        jButton8.setToolTipText("Do you want toexit ?");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Update");
        jButton5.setToolTipText("Do you want to update groups ?");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel31.setText("Service Group ID");

        jTextField4.setToolTipText("Please enter service group ID here to edit ");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 51, 51));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Serach");
        jButton9.setToolTipText("Do you want to search service groups ?");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel32.setText("Service Group ID");

        jLabel33.setEnabled(false);

        jButton10.setBackground(new java.awt.Color(255, 153, 255));
        jButton10.setText("Demo");
        jButton10.setToolTipText("Demo to test");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel31)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(2, 2, 2)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton5)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            if (jTextField1.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null, "Please Enter Employee ID"); 
            }
        
            else {
         try {
               Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
               
                rs = s.executeQuery("SELECT * FROM employee WHERE EmpID='" + jTextField1.getText() + "'");
              
                while (rs.next()) {
                    
                    jLabel7.setText(rs.getString("LName"));
                    jLabel8.setText(rs.getString("NIC"));
                    jLabel9.setText(rs.getString("Tel"));
                    jLabel10.setText(rs.getString("Address"));
                    
                }
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Invalid Employee ID");
            }
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void incre() {
         try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM service_group_details");
            while (rs.next()) {

                String ab = rs.getString("group_no");
                int ps = Integer.parseInt(ab);
                int ks = ps+1;
                 String ks1 = String.valueOf(ks);
                 jLabel33.setText(ks1);
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Servoce Group ID Fail");
            
        }  
    }
    
    public void Reset() {
        
        jLabel7.setText("");
        jLabel8.setText("");
        jLabel9.setText("");
        jLabel10.setText("");
        
        jLabel17.setText("");
        jLabel18.setText("");
        jLabel19.setText("");
        jLabel20.setText("");
        
        jLabel27.setText("");
        jLabel28.setText("");
        jLabel29.setText("");
        jLabel30.setText("");
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        
    }
    
     public void table() {

        DefaultTableModel dtf = (DefaultTableModel) jTable1.getModel();
        dtf.setRowCount(0);

        try {
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
            
            rs=s.executeQuery("SELECT * FROM service_group_details");

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("group_no"));
                v.add(rs.getString("leader_name"));
                v.add(rs.getString("leader_empno"));
                v.add(rs.getString("leader_tp"));
                v.add(rs.getString("leader_add"));
                v.add(rs.getString("member1_name"));
                v.add(rs.getString("member1_empno"));
                v.add(rs.getString("member1_tp"));
                v.add(rs.getString("member1_add"));
                v.add(rs.getString("member2_name"));
                v.add(rs.getString("member2_empno"));
                v.add(rs.getString("member2_tp"));
                v.add(rs.getString("member2_add"));
                
                dtf.addRow(v);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Table load Fail");
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             if (jTextField2.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null, "Please Enter Employee ID"); 
            }
             else {
           try {
               Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
               
                rs = s.executeQuery("SELECT * FROM employee WHERE EmpID='" + jTextField2.getText() + "'");
              
                while (rs.next()) {
                    
                    jLabel17.setText(rs.getString("LName"));
                    jLabel18.setText(rs.getString("NIC"));
                    jLabel19.setText(rs.getString("Tel"));
                    jLabel20.setText(rs.getString("Address"));
                    
                }
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Invalid Employee ID");
            }
             }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             if (jTextField3.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null, "Please Enter Employee ID"); 
            }
             else {
        try {
               Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
               
                rs = s.executeQuery("SELECT * FROM employee WHERE EmpID='" + jTextField3.getText() + "'");
              
                while (rs.next()) {
                    
                    jLabel27.setText(rs.getString("LName"));
                    jLabel28.setText(rs.getString("NIC"));
                    jLabel29.setText(rs.getString("Tel"));
                    jLabel30.setText(rs.getString("Address"));
                    
                }
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Invalid Employee ID");
            }
             }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if(jTextField1.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Select Employee ID");
        } 
        
        else if (jTextField2.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Select Employee ID");
        }
        else if (jTextField3.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Select Employee ID");
        }
        
          else if (jLabel7.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Select valid Employee");
        }
        
             else if (jLabel17.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Select valid Employee");
        }
        
                else if (jLabel27.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Select valid Employee");
        }
        else {
                    
        // -------------------------------------------------------------
    
         try {
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();

               
                rs = s.executeQuery("SELECT * FROM service_group_details WHERE leader_empno='"+jTextField1.getText()+ "'");
                if (rs.next()) {
                  JOptionPane.showMessageDialog(null, "Leader already has a group");                
                }
                
                rs1 = s.executeQuery("SELECT * FROM service_group_details WHERE member1_empno='"+jTextField2.getText()+ "'");
                if(rs1.next()) {
                  JOptionPane.showMessageDialog(null, "Member 01 already has a group");  
                }
                
                rs2 = s.executeQuery("SELECT * FROM service_group_details WHERE member2_empno='"+jTextField3.getText()+ "'");
                if(rs2.next()) {
                  JOptionPane.showMessageDialog(null, "Member 02 already has a group");  
                }
   
                // -------------------------------------------------------------            
        
                else {
         try { 
             
            String sql = "INSERT INTO service_group_details(group_no,leader_name,leader_empno,leader_nic,leader_tp,leader_add,member1_name,member1_empno,member1_nic,member1_tp,member1_add,member2_name,member2_empno,member2_nic,member2_tp,member2_add) VALUES ('"+jLabel33.getText()+"','"+jLabel7.getText()+"','"+jTextField1.getText()+"','"+jLabel8.getText()+"','"+jLabel9.getText()+"','"+jLabel10.getText()+"','"+jLabel17.getText()+"','"+jTextField2.getText()+"','"+jLabel8.getText()+"','"+jLabel19.getText()+"','"+jLabel20.getText()+"','"+jLabel27.getText()+"','"+jTextField3.getText()+"','"+jLabel28.getText()+"','"+jLabel29.getText()+"','"+jLabel30.getText()+"')";
            pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Saved Successfully");
           
       
        table();
          Reset();
          incre();
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Data save Failed");
            }
               
                }
                
                } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Invalid Service Group ID");
            }                   
                }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                    jButton5.setEnabled(false);
                    jButton6.setEnabled(false);
                    jButton9.setEnabled(false);
                    jButton4.setEnabled(true);
                    jLabel33.setEnabled(true);
                    jTextField4.setEnabled(true);
        
        Reset();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

           if (jTextField4.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Enter Group ID");
        }
           else if(jTextField1.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Select Employee ID");
        } 
        
        else if (jTextField2.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Select Employee ID");
        }
        else if (jTextField3.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Select Employee ID");
        }
        
          else if (jLabel7.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Select valid Employee");
        }
        
             else if (jLabel17.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Select valid Employee");
        }
        
                else if (jLabel27.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Select valid Employee");
        }
           
           else {
                    // --------------------------------------------------
                    
                     try {
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();

               
                rs = s.executeQuery("SELECT * FROM service_group_details WHERE leader_empno='"+jTextField1.getText()+ "'");
                if (rs.next()) {
                  JOptionPane.showMessageDialog(null, "Leader already has a group");                
                }
                
                rs1 = s.executeQuery("SELECT * FROM service_group_details WHERE member1_empno='"+jTextField2.getText()+ "'");
                if(rs1.next()) {
                  JOptionPane.showMessageDialog(null, "Member 01 already has a group");  
                }
                
                rs2 = s.executeQuery("SELECT * FROM service_group_details WHERE member2_empno='"+jTextField3.getText()+ "'");
                if(rs2.next()) {
                  JOptionPane.showMessageDialog(null, "Member 02 already has a group");  
                }
   
                    
                    // --------------------------------------------------
        
                else {
        try {
            
                String sql = "UPDATE service_group_details set leader_name='" + jLabel7.getText() + "',leader_empno='" + jTextField1.getText() + "',leader_tp='" +jLabel9.getText() + "',leader_add='" + jLabel10.getText() + "',member1_name='" + jLabel17.getText() + "',member1_empno='" + jTextField2.getText() + "',member1_tp='" +jLabel19.getText()+ "',member1_add='" + jLabel20.getText() + "',member2_name='" + jLabel27.getText() + "',member2_empno='"+jTextField3.getText()+"',member2_tp='"+jLabel29.getText()+"',member2_add='"+jLabel30.getText()+"'  WHERE group_no='" + jTextField4.getText() + "'";
                pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Database Updated");
                
                table();
                Reset();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Database Update Fail");
            }
             } 
                     }catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Invalid Service Group ID");
           }
                     }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
         if (jTextField4.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Enter Group ID");
        }
           else {
        
        
        String sql = "delete from service_group_details where group_no=? ";
        try  { 
            pst = con.prepareStatement(sql);
            pst.setString(1, jTextField4.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Deleted");
            table();
              Reset();
                         
        }
            
            catch(Exception e){
                    
                    JOptionPane.showMessageDialog(null,"Delete Fail");
                    
                    }
         }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
                   
                    if (jTextField4.getText().isEmpty()) {
                       JOptionPane.showMessageDialog(null,"Please Enter Service Group ID"); 
                    }
        
                    else {
                        
                   
                    jButton5.setEnabled(true);
                    jButton6.setEnabled(true);       
        
        try {
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
               
                rs = s.executeQuery("SELECT * FROM service_group_details WHERE group_no='"+jTextField4.getText()+ "'");
                while (rs.next()) {
                    
                    jTextField1.setText(rs.getString("leader_empno"));
                    jTextField2.setText(rs.getString("member1_empno"));
                    jLabel7.setText(rs.getString("leader_name"));
                    jLabel8.setText(rs.getString("leader_nic"));
                    jLabel9.setText(rs.getString("leader_tp"));
                    jLabel10.setText(rs.getString("leader_add"));
                    jTextField3.setText(rs.getString("member2_empno"));
                    jLabel17.setText(rs.getString("member1_name"));
                    jLabel18.setText(rs.getString("member1_nic"));
                    jLabel19.setText(rs.getString("member1_tp"));
                    jLabel20.setText(rs.getString("member1_add"));
                    jLabel27.setText(rs.getString("member2_name"));
                    jLabel28.setText(rs.getString("member2_nic"));
                    jLabel29.setText(rs.getString("member2_tp"));
                    jLabel30.setText(rs.getString("member2_add"));
                    
                }
          } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Invalid Service Group ID");
            }
                    }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        
        jButton9.setEnabled(true);
        jButton4.setEnabled(false);
        jLabel33.setEnabled(false);
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        jLabel7.setText("Nimal Silva");
        jLabel8.setText("713337623V");
        jLabel9.setText("0716586363");
        jLabel10.setText("Malambe");
        
        jLabel17.setText("Kamal Perera");
        jLabel18.setText("883237643V");
        jLabel19.setText("0713233423");
        jLabel20.setText("Dehiwala");
        
        jLabel27.setText("Nuwan Kumara");
        jLabel28.setText("902122322V");
        jLabel29.setText("0703244387");
        jLabel30.setText("Kandy");
        
        jTextField1.setText("001");
        jTextField2.setText("008");
        jTextField3.setText("005");

        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        if (jTextField4.getText().isEmpty()) {
                    jButton5.setEnabled(false);
                    jButton6.setEnabled(false);
                    jButton9.setEnabled(false);
                    jButton4.setEnabled(true);
                    jLabel33.setEnabled(true);
                    jTextField4.setEnabled(true);
        
        Reset();
        }
        else {
                    jButton4.setEnabled(false);
                    jButton5.setEnabled(true);
                    jButton6.setEnabled(true);       
        
        try {
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
               
                rs = s.executeQuery("SELECT * FROM service_group_details WHERE group_no='"+jTextField4.getText()+ "'");
                while (rs.next()) {
                    
                    jTextField1.setText(rs.getString("leader_empno"));
                    jTextField2.setText(rs.getString("member1_empno"));
                    jLabel7.setText(rs.getString("leader_name"));
                    jLabel8.setText(rs.getString("leader_nic"));
                    jLabel9.setText(rs.getString("leader_tp"));
                    jLabel10.setText(rs.getString("leader_add"));
                    jTextField3.setText(rs.getString("member2_empno"));
                    jLabel17.setText(rs.getString("member1_name"));
                    jLabel18.setText(rs.getString("member1_nic"));
                    jLabel19.setText(rs.getString("member1_tp"));
                    jLabel20.setText(rs.getString("member1_add"));
                    jLabel27.setText(rs.getString("member2_name"));
                    jLabel28.setText(rs.getString("member2_nic"));
                    jLabel29.setText(rs.getString("member2_tp"));
                    jLabel30.setText(rs.getString("member2_add"));
                    
                }
          } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Invalid Service Group ID");
            }
        } 
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
 if(evt.getKeyCode()==KeyEvent.VK_ENTER) {       
         try {
               Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
               
                rs = s.executeQuery("SELECT * FROM employee WHERE EmpID='" + jTextField1.getText() + "'");
              
                while (rs.next()) {
                    
                    jLabel7.setText(rs.getString("LName"));
                    jLabel8.setText(rs.getString("NIC"));
                    jLabel9.setText(rs.getString("Tel"));
                    jLabel10.setText(rs.getString("Address"));
                    
                }
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Invalid Employee ID");
            }
           
 }
 else {
     jLabel7.setText("");
     jLabel8.setText("");
     jLabel9.setText("");
     jLabel10.setText("");
 }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
 if(evt.getKeyCode()==KeyEvent.VK_ENTER) {        
           try {
               Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
               
                rs = s.executeQuery("SELECT * FROM employee WHERE EmpID='" + jTextField2.getText() + "'");
              
                while (rs.next()) {
                    
                    jLabel17.setText(rs.getString("LName"));
                    jLabel18.setText(rs.getString("NIC"));
                    jLabel19.setText(rs.getString("Tel"));
                    jLabel20.setText(rs.getString("Address"));
                    
                }
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Invalid Employee ID");
            
             }
 }
 else {
     jLabel17.setText("");
     jLabel18.setText("");
     jLabel19.setText("");
     jLabel20.setText("");
 }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
 if(evt.getKeyCode()==KeyEvent.VK_ENTER) {     
        try {
               Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
               
                rs = s.executeQuery("SELECT * FROM employee WHERE EmpID='" + jTextField3.getText() + "'");
              
                while (rs.next()) {
                    
                    jLabel27.setText(rs.getString("LName"));
                    jLabel28.setText(rs.getString("NIC"));
                    jLabel29.setText(rs.getString("Tel"));
                    jLabel30.setText(rs.getString("Address"));
                    
                }
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Invalid Employee ID");
            }
 }   
 else {
     jLabel27.setText("");
     jLabel28.setText("");
     jLabel29.setText("");
     jLabel30.setText("");
 }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
      
         if(evt.getKeyCode()==KeyEvent.VK_ENTER) {                  
                   
                    jButton5.setEnabled(true);
                    jButton6.setEnabled(true);       
        
        try {
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
               
                rs = s.executeQuery("SELECT * FROM service_group_details WHERE group_no='"+jTextField4.getText()+ "'");
                while (rs.next()) {
                    
                    jTextField1.setText(rs.getString("leader_empno"));
                    jTextField2.setText(rs.getString("member1_empno"));
                    jLabel7.setText(rs.getString("leader_name"));
                    jLabel8.setText(rs.getString("leader_nic"));
                    jLabel9.setText(rs.getString("leader_tp"));
                    jLabel10.setText(rs.getString("leader_add"));
                    jTextField3.setText(rs.getString("member2_empno"));
                    jLabel17.setText(rs.getString("member1_name"));
                    jLabel18.setText(rs.getString("member1_nic"));
                    jLabel19.setText(rs.getString("member1_tp"));
                    jLabel20.setText(rs.getString("member1_add"));
                    jLabel27.setText(rs.getString("member2_name"));
                    jLabel28.setText(rs.getString("member2_nic"));
                    jLabel29.setText(rs.getString("member2_tp"));
                    jLabel30.setText(rs.getString("member2_add"));
                    
                }
          } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Invalid Service Group ID");
            }
         }
         else {
     jLabel27.setText("");
     jLabel28.setText("");
     jLabel29.setText("");
     jLabel30.setText("");
     jLabel17.setText("");
     jLabel18.setText("");
     jLabel19.setText("");
     jLabel20.setText("");
     jLabel7.setText("");
     jLabel8.setText("");
     jLabel9.setText("");
     jLabel10.setText("");
         }
    }//GEN-LAST:event_jTextField4KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
