
package itp;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Stocks_Returning extends javax.swing.JInternalFrame {
int timeRun = 0;
    Connection con= null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    
    public Stocks_Returning() {
        initComponents();
        con = DBconnect.connect();
        jButton2.setVisible(false);
        jButton4.setVisible(false);
        jButton7.setVisible(false);
        table();
        
        Calendar now = Calendar.getInstance();
		int month = now.get(Calendar.MONTH); 
                int date = now.get(Calendar.DATE); 
                int year = now.get(Calendar.YEAR);
                String Date = year + "-" + month + "-" + date;
                lblRDate.setText(Date);
        
          new Thread()
        {
            public void run()
            {
                while(timeRun==0)
                {
                    Calendar cal=new GregorianCalendar();
                    int hour=cal.get(Calendar.HOUR);
                    if(hour==0)
                    {
                        hour=hour+12;
                    }
                    int min=cal.get(Calendar.MINUTE);
                    int sec=cal.get(Calendar.SECOND);
                    int AM_PM=cal.get(Calendar.AM_PM);
            
            
                    String day_night=""; 
                    if(AM_PM==1)
                    {
                        day_night="PM";
                    }
                    else
                    {
                        day_night="AM";
                    }
            
                    String time =hour+":"+min+":"+sec+""+day_night;
            
                    lblRTime.setText(time);
                }
            }
        }.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblSG = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblSCost = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbllend = new javax.swing.JLabel();
        lblCName = new javax.swing.JLabel();
        lblSType = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblRDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblRTime = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        lblIQ1 = new javax.swing.JLabel();
        lblIQ2 = new javax.swing.JLabel();
        lblIQ3 = new javax.swing.JLabel();
        lblIQ4 = new javax.swing.JLabel();
        lblIQ5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        lblUQ1 = new javax.swing.JLabel();
        lblUQ2 = new javax.swing.JLabel();
        lblUQ3 = new javax.swing.JLabel();
        lblUQ4 = new javax.swing.JLabel();
        lblUQ5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        txtRQ1 = new javax.swing.JTextField();
        txtRQ2 = new javax.swing.JTextField();
        txtRQ3 = new javax.swing.JTextField();
        txtRQ4 = new javax.swing.JTextField();
        txtRQ5 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        lblBQ1 = new javax.swing.JLabel();
        lblBQ2 = new javax.swing.JLabel();
        lblBQ3 = new javax.swing.JLabel();
        lblBQ4 = new javax.swing.JLabel();
        lblBQ5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Return Stock Items");
        setEnabled(false);
        setMaximumSize(new java.awt.Dimension(1035, 620));
        setMinimumSize(new java.awt.Dimension(1035, 620));
        setPreferredSize(new java.awt.Dimension(1035, 620));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(324, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(324, 51));

        jLabel1.setText("Lending ID");

        txtSID.setToolTipText("please enter lend ID to here");
        txtSID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSIDKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.setToolTipText("Search the lend details");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtSID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMaximumSize(new java.awt.Dimension(297, 92));
        jPanel2.setMinimumSize(new java.awt.Dimension(297, 92));

        jLabel2.setText("Service Group No ");

        lblSG.setEnabled(false);

        jLabel16.setText("Customer ID");

        lblSCost.setEnabled(false);

        jLabel24.setText("Service ID");

        lblDesc.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSCost, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(lblDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblSG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblSCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setMaximumSize(new java.awt.Dimension(301, 174));
        jPanel3.setMinimumSize(new java.awt.Dimension(301, 174));

        jLabel12.setText("Lend Date");

        jLabel13.setText("Lend Time");

        jLabel17.setText("Service Type ");

        lbllend.setEnabled(false);

        lblCName.setEnabled(false);

        lblSType.setEnabled(false);

        jLabel5.setText("Return Date");

        lblRDate.setEnabled(false);

        jLabel6.setText("Return Time ");

        lblRTime.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel17)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblCName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(lbllend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblRTime, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRDate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSType, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblSType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbllend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblCName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblRDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblRTime))
                .addGap(43, 43, 43))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setMaximumSize(new java.awt.Dimension(79, 136));
        jPanel4.setMinimumSize(new java.awt.Dimension(79, 136));

        jLabel26.setText("Item No");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setEnabled(false);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setEnabled(false);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setEnabled(false);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setEnabled(false);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel26))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(17, 17, 17))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setMaximumSize(new java.awt.Dimension(104, 136));
        jPanel6.setMinimumSize(new java.awt.Dimension(104, 136));

        jLabel28.setText("Issue Quantity");

        lblIQ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIQ1.setEnabled(false);

        lblIQ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIQ2.setEnabled(false);

        lblIQ3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIQ3.setEnabled(false);

        lblIQ4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIQ4.setEnabled(false);

        lblIQ5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIQ5.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIQ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIQ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIQ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIQ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(9, 9, 9))
                    .addComponent(lblIQ5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(lblIQ1)
                .addGap(18, 18, 18)
                .addComponent(lblIQ2)
                .addGap(18, 18, 18)
                .addComponent(lblIQ3)
                .addGap(18, 18, 18)
                .addComponent(lblIQ4)
                .addGap(18, 18, 18)
                .addComponent(lblIQ5)
                .addGap(17, 17, 17))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setMaximumSize(new java.awt.Dimension(103, 136));
        jPanel7.setMinimumSize(new java.awt.Dimension(104, 136));

        jLabel29.setText("Use Quantity");

        lblUQ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUQ1.setEnabled(false);

        lblUQ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUQ2.setEnabled(false);

        lblUQ3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUQ3.setEnabled(false);

        lblUQ4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUQ4.setEnabled(false);

        lblUQ5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUQ5.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUQ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUQ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUQ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUQ5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUQ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(lblUQ1)
                .addGap(18, 18, 18)
                .addComponent(lblUQ2)
                .addGap(18, 18, 18)
                .addComponent(lblUQ3)
                .addGap(18, 18, 18)
                .addComponent(lblUQ4)
                .addGap(18, 18, 18)
                .addComponent(lblUQ5)
                .addGap(17, 17, 17))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setMaximumSize(new java.awt.Dimension(104, 170));
        jPanel8.setMinimumSize(new java.awt.Dimension(104, 170));

        jLabel30.setText("Return Quantity");

        txtRQ1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRQ1KeyTyped(evt);
            }
        });

        txtRQ2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRQ2KeyTyped(evt);
            }
        });

        txtRQ3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRQ3KeyTyped(evt);
            }
        });

        txtRQ4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRQ4KeyTyped(evt);
            }
        });

        txtRQ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRQ5ActionPerformed(evt);
            }
        });
        txtRQ5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRQ5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRQ1)
                    .addComponent(txtRQ2)
                    .addComponent(txtRQ3)
                    .addComponent(txtRQ4)
                    .addComponent(txtRQ5))
                .addGap(12, 12, 12))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtRQ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRQ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setMaximumSize(new java.awt.Dimension(102, 136));
        jPanel9.setMinimumSize(new java.awt.Dimension(102, 136));

        jLabel31.setText("Balance Qty.");

        lblBQ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblBQ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblBQ3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblBQ4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblBQ5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBQ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBQ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBQ5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBQ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBQ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(lblBQ1)
                .addGap(18, 18, 18)
                .addComponent(lblBQ2)
                .addGap(18, 18, 18)
                .addComponent(lblBQ3)
                .addGap(18, 18, 18)
                .addComponent(lblBQ4)
                .addGap(18, 18, 18)
                .addComponent(lblBQ5)
                .addGap(17, 17, 17))
        );

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Upload");
        jButton2.setToolTipText("Upload return items to the sub stock");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 51, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Message");
        jButton4.setToolTipText("Do you want to inform to the manager ?");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Clear");
        jButton5.setToolTipText("Reset everythings");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Lending ID", "Group ID", "Customer ID", "Lend Date", "Return Date", "Lend Time", "Return Time", "Item No", "Qty", "Item No", "Qty", "Item No", "Qty", "Item No", "Qty", "Item No", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable2);

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setMaximumSize(new java.awt.Dimension(103, 136));
        jPanel11.setMinimumSize(new java.awt.Dimension(103, 136));

        jLabel3.setText("Status");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(17, 17, 17))
        );

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Use Qty");
        jButton3.setToolTipText("Check the use qty with issue reports");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 51, 51));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Check");
        jButton7.setToolTipText("check the differnce between use qty and return qty");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 153, 255));
        jButton8.setText("Demo");
        jButton8.setToolTipText("Demo to test");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(150, 150, 150))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Reset() {
     txtSID.setText("");
     lblSG.setText("");

     jButton2.setVisible(false);
     jButton4.setVisible(false);
     jButton7.setVisible(false);

     lbllend.setText("");
     lblCName.setText("");

     lblSType.setText("");
     lblSCost.setText("");
     lblDesc.setText("");

     lblIQ1.setText("");
     lblIQ2.setText("");
     lblIQ3.setText("");
     lblIQ4.setText("");
     lblIQ5.setText("");
     lblUQ1.setText("");
     lblUQ2.setText("");
     lblUQ3.setText("");
     lblUQ4.setText("");
     lblUQ5.setText("");
     txtRQ1.setText("");
     txtRQ2.setText("");
     txtRQ3.setText("");
     txtRQ4.setText("");
     txtRQ5.setText("");
     lblBQ1.setText("");
     lblBQ2.setText("");
     lblBQ3.setText("");
     lblBQ4.setText("");
     lblBQ5.setText("");
     
     jLabel4.setText("");
     jLabel14.setText("");
     jLabel15.setText("");
     jLabel18.setText("");
     jLabel19.setText("");
     jLabel7.setText("");
     jLabel8.setText("");
     jLabel9.setText("");
     jLabel10.setText("");
     jLabel11.setText("");

    }
    
    private void txtRQ1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRQ1KeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtRQ1KeyTyped

    private void txtRQ2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRQ2KeyTyped
       char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtRQ2KeyTyped

    private void txtRQ3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRQ3KeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtRQ3KeyTyped

    private void txtRQ4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRQ4KeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtRQ4KeyTyped

    private void txtRQ5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRQ5KeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtRQ5KeyTyped

    
     public void table() {

        DefaultTableModel dtf = (DefaultTableModel) jTable2.getModel();
        dtf.setRowCount(0);

        try {
                java.sql.Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
            
            rs=s.executeQuery("SELECT * FROM lending_returning_details");

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("lr_no"));
                v.add(rs.getString("group_no"));
                v.add(rs.getString("customer_id"));
                v.add(rs.getString("lend_date"));
                v.add(rs.getString("return_date"));
                v.add(rs.getString("lend_time"));
                v.add(rs.getString("return_time"));
                v.add(rs.getString("item_no1"));
                v.add(rs.getString("qty11"));
                v.add(rs.getString("item_no2"));
                v.add(rs.getString("qty22"));
                v.add(rs.getString("item_no3"));
                v.add(rs.getString("qty33"));
                v.add(rs.getString("item_no4"));
                v.add(rs.getString("qty44"));
                v.add(rs.getString("item_no5"));
                v.add(rs.getString("qty55"));
          
                            
                dtf.addRow(v);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Table load Fail");
        }
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Reset();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtSID.getText().isEmpty()) {
          JOptionPane.showMessageDialog(null, "Please Enter Lending ID");  
        }
        else {
        
        try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM lending_returning_details WHERE lr_no='" + txtSID.getText() + "'");
            while (rs.next()) {

                lblSG.setText(rs.getString("group_no"));                
                lblSCost.setText(rs.getString("customer_id"));
                lbllend.setText(rs.getString("lend_date"));                
                lblCName.setText(rs.getString("lend_time"));
                
                jLabel7.setText(rs.getString("item_no1"));                
                lblIQ1.setText(rs.getString("qty1"));  
                
                jLabel8.setText(rs.getString("item_no2"));                
                lblIQ2.setText(rs.getString("qty2"));
                
                jLabel9.setText(rs.getString("item_no3"));                
                lblIQ3.setText(rs.getString("qty3"));
                
                jLabel10.setText(rs.getString("item_no4"));                
                lblIQ4.setText(rs.getString("qty4"));
                
                jLabel11.setText(rs.getString("item_no5"));                
                lblIQ5.setText(rs.getString("qty5"));
                
                lblDesc.setText(rs.getString("service_id")); 
                lblSType.setText(rs.getString("s_type"));
                
         }         
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Lending ID");
            
        }        
        }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txtSID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Lending ID");
        }
        
        else if(lblSG.getText().isEmpty()) {
          JOptionPane.showMessageDialog(null, "Please enter correct Lending ID");  
        }
        else {
        
        try {
                 
                String sql = "UPDATE lending_returning_details set return_date='" + lblRDate.getText() + "',return_time='" + lblRTime.getText() + "',qty11='" + txtRQ1.getText() + "',qty22='" + txtRQ2.getText() + "',qty33='" + txtRQ3.getText() + "',qty44='" + txtRQ4.getText() + "',qty55='" + txtRQ5.getText() +"' WHERE lr_no='" + txtSID.getText() + "'";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Updated Successfully");
              table();
                Reset();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Updated not Successfully");
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton7.setVisible(true);   
        
        if(lblSType.getText().startsWith("Fix")) {
        
         try {
            
             Connection conn = DBconnect.connect();
               Statement s1 = conn.createStatement();
               
            rs = s1.executeQuery("SELECT * FROM fixing_service WHERE fixing_id='" + lblDesc.getText() + "'");
       
            while (rs.next()) {
                             
                String a = rs.getString("qty1");
                String b = rs.getString("qty2");
                String c = rs.getString("qty3");
                String d = rs.getString("qty4");
                String e = rs.getString("qty5");
                
                String a1 = rs.getString("item_no1");
                String b1 = rs.getString("item_no2");
                String c1 = rs.getString("item_no3");
                String d1 = rs.getString("item_no4");
                String e1 = rs.getString("item_no4");
                
                String a11 = jLabel7.getText().toString();
                String b11 = jLabel8.getText().toString();
                String c11 = jLabel9.getText().toString();
                String d11 = jLabel10.getText().toString();
                String e11 = jLabel11.getText().toString();
                
                if(a11.equals(a1)) {
                    lblUQ1.setText(a);
                }
                else if (a11.equals(b1)) {
                    lblUQ1.setText(b);
                }
                else if (a11.equals(c1)) {
                    lblUQ1.setText(c);
                }
                else if (a11.equals(d1)) {
                    lblUQ1.setText(d);
                }
                else if (a11.equals(e1)) {
                    lblUQ1.setText(e);
                }
                else
                    lblUQ1.setText("0");
                
                if(b11.equals(a1)) {
                    lblUQ2.setText(a);
                }
                else if (b11.equals(b1)) {
                    lblUQ2.setText(b);
                }
                else if (b11.equals(c1)) {
                    lblUQ2.setText(c);
                }
                else if (b11.equals(d1)) {
                    lblUQ2.setText(d);
                }
                else if (b11.equals(e1)) {
                    lblUQ2.setText(e);
                }
                else
                    lblUQ2.setText("0");
                
                if(c11.equals(a1)) {
                    lblUQ3.setText(a);
                }
                else if (c11.equals(b1)) {
                    lblUQ3.setText(b);
                }
                else if (c11.equals(c1)) {
                    lblUQ3.setText(c);
                }
                else if (c11.equals(d1)) {
                    lblUQ3.setText(d);
                }
                else if (c11.equals(e1)) {
                    lblUQ3.setText(e);
                }
                else
                    lblUQ3.setText("0");
                
                if(d11.equals(a1)) {
                    lblUQ4.setText(a);
                }
                else if (d11.equals(b1)) {
                    lblUQ4.setText(b);
                }
                else if (d11.equals(c1)) {
                    lblUQ4.setText(c);
                }
                else if (d11.equals(d1)) {
                    lblUQ4.setText(d);
                }
                else if (d11.equals(e1)) {
                    lblUQ4.setText(e);
                }
                else
                    lblUQ4.setText("0");
                
                if(e11.equals(a1)) {
                    lblUQ5.setText(a);
                }
                else if (e11.equals(b1)) {
                    lblUQ5.setText(b);
                }
                else if (e11.equals(c1)) {
                    lblUQ5.setText(c);
                }
                else if (e11.equals(d1)) {
                    lblUQ5.setText(d);
                }
                else if (e11.equals(e1)) {
                    lblUQ5.setText(e);
                }
                else
                    lblUQ5.setText("0");
               
         }
           
        } catch (Exception e) {

            
        }        
        }
        else {
        
        
        try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
                      
            rs = s.executeQuery("SELECT * FROM after_service_details WHERE service_id='" + lblDesc.getText() + "'");
            while (rs.next()) {
                             
                String a = rs.getString("use_qty_1");
                String b = rs.getString("use_qty_2");
                String c = rs.getString("use_qty_3");
                String d = rs.getString("use_qty_4");
                String e = rs.getString("use_qty_5");
                
                String a1 = rs.getString("item");
                String b1 = rs.getString("item_no_2");
                String c1 = rs.getString("item_no_3");
                String d1 = rs.getString("item_no_4");
                String e1 = rs.getString("item_no_4");
 
                String a11 = jLabel7.getText().toString();
                String b11 = jLabel8.getText().toString();
                String c11 = jLabel9.getText().toString();
                String d11 = jLabel10.getText().toString();
                String e11 = jLabel11.getText().toString();
                
                if(a11.equals(a1)) {
                    lblUQ1.setText(a);
                }
                else if (a11.equals(b1)) {
                    lblUQ1.setText(b);
                }
                else if (a11.equals(c1)) {
                    lblUQ1.setText(c);
                }
                else if (a11.equals(d1)) {
                    lblUQ1.setText(d);
                }
                else if (a11.equals(e1)) {
                    lblUQ1.setText(e);
                }
                else
                    lblUQ1.setText("0");
                
                if(b11.equals(a1)) {
                    lblUQ2.setText(a);
                }
                else if (b11.equals(b1)) {
                    lblUQ2.setText(b);
                }
                else if (b11.equals(c1)) {
                    lblUQ2.setText(c);
                }
                else if (b11.equals(d1)) {
                    lblUQ2.setText(d);
                }
                else if (b11.equals(e1)) {
                    lblUQ2.setText(e);
                }
                else
                    lblUQ2.setText("0");
                
                if(c11.equals(a1)) {
                    lblUQ3.setText(a);
                }
                else if (c11.equals(b1)) {
                    lblUQ3.setText(b);
                }
                else if (c11.equals(c1)) {
                    lblUQ3.setText(c);
                }
                else if (c11.equals(d1)) {
                    lblUQ3.setText(d);
                }
                else if (c11.equals(e1)) {
                    lblUQ3.setText(e);
                }
                else
                    lblUQ3.setText("0");
                
                if(d11.equals(a1)) {
                    lblUQ4.setText(a);
                }
                else if (d11.equals(b1)) {
                    lblUQ4.setText(b);
                }
                else if (d11.equals(c1)) {
                    lblUQ4.setText(c);
                }
                else if (d11.equals(d1)) {
                    lblUQ4.setText(d);
                }
                else if (d11.equals(e1)) {
                    lblUQ4.setText(e);
                }
                else
                    lblUQ4.setText("0");
                
                if(e11.equals(a1)) {
                    lblUQ5.setText(a);
                }
                else if (e11.equals(b1)) {
                    lblUQ5.setText(b);
                }
                else if (e11.equals(c1)) {
                    lblUQ5.setText(c);
                }
                else if (e11.equals(d1)) {
                    lblUQ5.setText(d);
                }
                else if (e11.equals(e1)) {
                    lblUQ5.setText(e);
                }
                else
                    lblUQ5.setText("0");
               
         }
           
        } catch (Exception e) {

            
        }        
       
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jButton4.setVisible(true);
        jButton2.setVisible(true);
        
        String a = lblIQ1.getText();
        String b = lblIQ2.getText();
        String c = lblIQ3.getText();
        String d = lblIQ4.getText();
        String e = lblIQ5.getText();
        
        int a1 = Integer.parseInt(a);
        int b1 = Integer.parseInt(b);
        int c1 = Integer.parseInt(c);
        int d1 = Integer.parseInt(d);
        int e1 = Integer.parseInt(e);
        
        String f = lblUQ1.getText();
        String g = lblUQ2.getText();
        String h = lblUQ3.getText();
        String i = lblUQ4.getText();
        String j = lblUQ5.getText();
        
        int f1 = Integer.parseInt(f);
        int g1 = Integer.parseInt(g);
        int h1 = Integer.parseInt(h);
        int i1 = Integer.parseInt(i);
        int j1 = Integer.parseInt(j);
        
        String k = txtRQ1.getText();
        String l = txtRQ2.getText();
        String m = txtRQ3.getText();
        String n = txtRQ4.getText();
        String o = txtRQ5.getText();
        
        int k1 = Integer.parseInt(k);
        int l1 = Integer.parseInt(l);
        int m1 = Integer.parseInt(m);
        int n1 = Integer.parseInt(n);
        int o1 = Integer.parseInt(o);
        
        int Dif1 = a1 - (f1+k1); 
        int Dif2 = b1 - (g1+l1);
        int Dif3 = c1 - (h1+m1);
        int Dif4 = d1 - (i1+n1);
        int Dif5 = e1 - (j1+o1);
        
        String di1 = String.valueOf(Dif1);
        String di2 = String.valueOf(Dif2);
        String di3 = String.valueOf(Dif3);
        String di4 = String.valueOf(Dif4);
        String di5 = String.valueOf(Dif5);
        
        lblBQ1.setText(di1);
        lblBQ2.setText(di2);
        lblBQ3.setText(di3);
        lblBQ4.setText(di4);
        lblBQ5.setText(di5);
        
        if (Dif1 == 0) {
            jLabel4.setText("OK");
        }
        else {
            jLabel4.setText("Missing");
            jLabel4.setForeground(Color.RED);
        }
        if (Dif2 == 0) {
            jLabel14.setText("OK");
        }
        else {
            jLabel14.setText("Missing");
            jLabel14.setForeground(Color.RED);
        }
        if (Dif3 == 0) {
            jLabel15.setText("OK");
            
        }
        else {
            jLabel15.setText("Missing");
            jLabel15.setForeground(Color.RED);
        }    
        if (Dif4 == 0) {
            jLabel18.setText("OK");
        }
        else {
            jLabel18.setText("Missing");
            jLabel18.setForeground(Color.RED);
        }
        
        if (Dif5 == 0) {
            jLabel19.setText("OK");
        }
        else {
            jLabel19.setText("Missing");
            jLabel19.setForeground(Color.RED);
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
/*     txtSID.setText("6");
     lblSG.setText("3");

     lbllend.setText("08-16-2016");
     lblCName.setText("03:43:32 PM");

     lblSType.setText("Fixing Service");
     lblSCost.setText("11");
     lblDesc.setText("4");

     lblIQ1.setText("4");
     lblIQ2.setText("3");
     lblIQ3.setText("3");
     lblIQ4.setText("4");
     lblIQ5.setText("2");
     lblUQ1.setText("3");
     lblUQ2.setText("2");
     lblUQ3.setText("3");
     lblUQ4.setText("3");
     lblUQ5.setText("1"); */
     txtRQ1.setText("1");
     txtRQ2.setText("1");
     txtRQ3.setText("0");
     txtRQ4.setText("0");
     txtRQ5.setText("1");
    /* lblBQ1.setText("0");
     lblBQ2.setText("0");
     lblBQ3.setText("0");
     lblBQ4.setText("1"); 
     lblBQ5.setText("0"); 
     
     jLabel7.setText("Item 004");
     jLabel8.setText("Item 006");
     jLabel9.setText("Item 003");
     jLabel10.setText("Item 001");
     jLabel11.setText("Item 007");
     
     jLabel4.setText("OK");
     jLabel14.setText("OK");
     jLabel15.setText("OK");
     jLabel18.setText("FALSE");
     jLabel19.setText("OK"); */
     
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtRQ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRQ5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRQ5ActionPerformed

    private void txtSIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSIDKeyReleased
/*        
        if(txtSID.getText().isEmpty()) {
            Reset();
        }
        else {
        try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM lending_returning_details WHERE lr_no='" + txtSID.getText() + "'");
            while (rs.next()) {

                lblSG.setText(rs.getString("group_no"));                
                lblSCost.setText(rs.getString("customer_id"));
                lbllend.setText(rs.getString("lend_date"));                
                lblCName.setText(rs.getString("lend_time"));
                
                jLabel7.setText(rs.getString("item_no1"));                
                lblIQ1.setText(rs.getString("qty1"));  
                
                jLabel8.setText(rs.getString("item_no2"));                
                lblIQ2.setText(rs.getString("qty2"));
                
                jLabel9.setText(rs.getString("item_no3"));                
                lblIQ3.setText(rs.getString("qty3"));
                
                jLabel10.setText(rs.getString("item_no4"));                
                lblIQ4.setText(rs.getString("qty4"));
                
                jLabel11.setText(rs.getString("item_no5"));                
                lblIQ5.setText(rs.getString("qty5"));
                
                lblDesc.setText(rs.getString("service_id")); 
                lblSType.setText(rs.getString("s_type"));
                
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Lending ID");
            
        }        
       
        }
     */   
         
    }//GEN-LAST:event_txtSIDKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Message msg = new Message();
        msg.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtSIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSIDKeyPressed
 if(evt.getKeyCode()==KeyEvent.VK_ENTER) {      
        try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM lending_returning_details WHERE lr_no='" + txtSID.getText() + "'");
            while (rs.next()) {

                lblSG.setText(rs.getString("group_no"));                
                lblSCost.setText(rs.getString("customer_id"));
                lbllend.setText(rs.getString("lend_date"));                
                lblCName.setText(rs.getString("lend_time"));
                
                jLabel7.setText(rs.getString("item_no1"));                
                lblIQ1.setText(rs.getString("qty1"));  
                
                jLabel8.setText(rs.getString("item_no2"));                
                lblIQ2.setText(rs.getString("qty2"));
                
                jLabel9.setText(rs.getString("item_no3"));                
                lblIQ3.setText(rs.getString("qty3"));
                
                jLabel10.setText(rs.getString("item_no4"));                
                lblIQ4.setText(rs.getString("qty4"));
                
                jLabel11.setText(rs.getString("item_no5"));                
                lblIQ5.setText(rs.getString("qty5"));
                
                lblDesc.setText(rs.getString("service_id")); 
                lblSType.setText(rs.getString("s_type"));
                
         }         
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Lending ID");
            
        }        
 }
 else {
     lblSG.setText("");
     lblSCost.setText("");
     lbllend.setText("");
     lblCName.setText("");
     jLabel7.setText("");
     jLabel8.setText("");
     jLabel9.setText("");
     jLabel10.setText("");
     jLabel11.setText("");
     lblIQ1.setText("");
     lblIQ2.setText("");
     lblIQ3.setText("");
     lblIQ4.setText("");
     lblIQ5.setText("");
     lblDesc.setText("");
     lblSType.setText("");
     
 }
 
    }//GEN-LAST:event_txtSIDKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblBQ1;
    private javax.swing.JLabel lblBQ2;
    private javax.swing.JLabel lblBQ3;
    private javax.swing.JLabel lblBQ4;
    private javax.swing.JLabel lblBQ5;
    private javax.swing.JLabel lblCName;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblIQ1;
    private javax.swing.JLabel lblIQ2;
    private javax.swing.JLabel lblIQ3;
    private javax.swing.JLabel lblIQ4;
    private javax.swing.JLabel lblIQ5;
    private javax.swing.JLabel lblRDate;
    private javax.swing.JLabel lblRTime;
    private javax.swing.JLabel lblSCost;
    private javax.swing.JLabel lblSG;
    private javax.swing.JLabel lblSType;
    private javax.swing.JLabel lblUQ1;
    private javax.swing.JLabel lblUQ2;
    private javax.swing.JLabel lblUQ3;
    private javax.swing.JLabel lblUQ4;
    private javax.swing.JLabel lblUQ5;
    private javax.swing.JLabel lbllend;
    private javax.swing.JTextField txtRQ1;
    private javax.swing.JTextField txtRQ2;
    private javax.swing.JTextField txtRQ3;
    private javax.swing.JTextField txtRQ4;
    private javax.swing.JTextField txtRQ5;
    private javax.swing.JTextField txtSID;
    // End of variables declaration//GEN-END:variables
}
