
package itp;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Stocks_Lending extends javax.swing.JInternalFrame {
int timeRun = 0;
    Connection con= null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    
    public Stocks_Lending() {
        initComponents();
        con = DBconnect.connect();
        jButton3.setVisible(false);
        
        txtIQ1.setEnabled(false);
        txtIQ2.setEnabled(false);
        txtIQ3.setEnabled(false);
        txtIQ4.setEnabled(false);
       txtIQ5.setEnabled(false);
        
        table();
        
          incre(); 
        
        
         Calendar now = Calendar.getInstance();
		int month = now.get(Calendar.MONTH); 
                int date = now.get(Calendar.DATE); 
                int year = now.get(Calendar.YEAR);
                String Date = year + "-" + month + "-" + date;
                lblDate.setText(Date);
                
                  new Thread()
        {
            public void run()
            {
                while(timeRun==0)
                {
                    Calendar cal=new GregorianCalendar();
                    int hour=cal.get(Calendar.HOUR);
                    if(hour==0)
                    {
                        hour=hour+12;
                    }
                    int min=cal.get(Calendar.MINUTE);
                    int sec=cal.get(Calendar.SECOND);
                    int AM_PM=cal.get(Calendar.AM_PM);
            
            
                    String day_night=""; 
                    if(AM_PM==1)
                    {
                        day_night="PM";
                    }
                    else
                    {
                        day_night="AM";
                    }
            
                    String time =hour+":"+min+":"+sec+""+day_night;
            
                    lblTime.setText(time);
                }
            }
        }.start();
                  
                  
                  
                  
                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSGN = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblSGL = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblEID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCID = new javax.swing.JTextField();
        lblCName = new javax.swing.JLabel();
        lblCTP = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblAddress = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblM1 = new javax.swing.JLabel();
        lblM2 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lblEID1 = new javax.swing.JLabel();
        lblEID2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        cmb1 = new javax.swing.JComboBox<>();
        cmb2 = new javax.swing.JComboBox<>();
        cmb3 = new javax.swing.JComboBox<>();
        cmb4 = new javax.swing.JComboBox<>();
        cmb5 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        lblIN1 = new javax.swing.JLabel();
        lblIN2 = new javax.swing.JLabel();
        lblIN3 = new javax.swing.JLabel();
        lblIN4 = new javax.swing.JLabel();
        lblIN5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtIQ1 = new javax.swing.JTextField();
        txtIQ2 = new javax.swing.JTextField();
        txtIQ3 = new javax.swing.JTextField();
        txtIQ4 = new javax.swing.JTextField();
        txtIQ5 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        lblUP1 = new javax.swing.JLabel();
        lblUP2 = new javax.swing.JLabel();
        lblUP3 = new javax.swing.JLabel();
        lblUP4 = new javax.swing.JLabel();
        lblUP5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        lblTP1 = new javax.swing.JLabel();
        lblTP2 = new javax.swing.JLabel();
        lblTP3 = new javax.swing.JLabel();
        lblTP4 = new javax.swing.JLabel();
        lblTP5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblNOIQ = new javax.swing.JLabel();
        lblNOIQP = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        lblSID = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setTitle("Lending Stock Items");
        setMaximumSize(new java.awt.Dimension(1035, 620));
        setMinimumSize(new java.awt.Dimension(1035, 620));
        setPreferredSize(new java.awt.Dimension(1035, 620));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(299, 152));
        jPanel1.setMinimumSize(new java.awt.Dimension(299, 152));

        jLabel1.setText("Service Group No         ");

        txtSGN.setToolTipText("please enter group ID here");
        txtSGN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSGNKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSGNKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.setToolTipText("Do you want to search the groups ?");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Service Group Leader");

        lblSGL.setEnabled(false);

        jLabel6.setText("Employee ID    ");

        lblEID.setEnabled(false);

        jLabel3.setText("Leader Telephone");

        lblTP.setEnabled(false);

        jLabel4.setText("Date            ");

        lblDate.setEnabled(false);

        jLabel5.setText("Time   ");

        lblTime.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(54, 54, 54)
                        .addComponent(lblEID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSGN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(lblSGL, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSGN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblSGL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblEID))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTime))
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMaximumSize(new java.awt.Dimension(297, 154));
        jPanel2.setMinimumSize(new java.awt.Dimension(297, 154));

        jLabel13.setText("Customer ID                ");

        jLabel14.setText("Customer Name  ");

        jLabel15.setText("Customer Telephone");

        jLabel16.setText("Address                       ");

        txtCID.setToolTipText("please enter customer ID here");
        txtCID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCIDKeyReleased(evt);
            }
        });

        lblCName.setEnabled(false);

        lblCTP.setEnabled(false);

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search");
        jButton2.setToolTipText("Do you want to search the customer details ?");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblAddress.setEditable(false);
        lblAddress.setColumns(20);
        lblAddress.setRows(5);
        lblAddress.setToolTipText("you cannot edit this");
        lblAddress.setEnabled(false);
        jScrollPane1.setViewportView(lblAddress);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtCID, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(45, 45, 45)
                        .addComponent(lblCName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(27, 27, 27))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(15, 15, 15)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblCTP, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblCName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblCTP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(38, 38, 38))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setMaximumSize(new java.awt.Dimension(568, 75));
        jPanel4.setMinimumSize(new java.awt.Dimension(568, 75));

        jLabel25.setText("Other Group Members");

        jLabel26.setText("Member 1 Nam");

        jLabel27.setText("Member 2 Name ");

        lblM1.setEnabled(false);

        lblM2.setEnabled(false);

        jLabel32.setText("Employee ID  ");

        jLabel33.setText("Employee ID ");

        lblEID1.setEnabled(false);

        lblEID2.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(45, 45, 45)
                                .addComponent(lblM1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(36, 36, 36)
                                .addComponent(lblM2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(48, 48, 48)
                                .addComponent(lblEID2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(45, 45, 45)
                                .addComponent(lblEID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(lblM1)
                    .addComponent(jLabel32)
                    .addComponent(lblEID1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblM2)
                    .addComponent(jLabel33)
                    .addComponent(lblEID2))
                .addGap(10, 10, 10))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setMaximumSize(new java.awt.Dimension(114, 164));
        jPanel3.setMinimumSize(new java.awt.Dimension(114, 164));

        jLabel21.setText("Item No");

        cmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1ActionPerformed(evt);
            }
        });

        cmb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb2ActionPerformed(evt);
            }
        });

        cmb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb3ActionPerformed(evt);
            }
        });

        cmb4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb4ActionPerformed(evt);
            }
        });

        cmb5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 001", "Item 002", "Item 003", "Item 004", "Item 005", "Item 006", "Item 007", "Item 008" }));
        cmb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb1, 0, 90, Short.MAX_VALUE)
                    .addComponent(cmb3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setMaximumSize(new java.awt.Dimension(124, 126));
        jPanel5.setMinimumSize(new java.awt.Dimension(124, 126));

        jLabel22.setText("Item Name");

        lblIN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN1.setEnabled(false);

        lblIN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN2.setEnabled(false);

        lblIN3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN3.setEnabled(false);

        lblIN4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN4.setEnabled(false);

        lblIN5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN5.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIN5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIN4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIN3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIN2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel22)
                .addGap(36, 36, 36))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIN1)
                .addGap(21, 21, 21)
                .addComponent(lblIN2)
                .addGap(18, 18, 18)
                .addComponent(lblIN3)
                .addGap(18, 18, 18)
                .addComponent(lblIN4)
                .addGap(18, 18, 18)
                .addComponent(lblIN5)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setMaximumSize(new java.awt.Dimension(116, 159));
        jPanel6.setMinimumSize(new java.awt.Dimension(116, 159));

        jLabel23.setText("Issue Quantity");

        txtIQ1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIQ1KeyTyped(evt);
            }
        });

        txtIQ2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIQ2KeyTyped(evt);
            }
        });

        txtIQ3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIQ3KeyTyped(evt);
            }
        });

        txtIQ4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIQ4KeyTyped(evt);
            }
        });

        txtIQ5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIQ5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIQ1)
                    .addComponent(txtIQ2)
                    .addComponent(txtIQ3)
                    .addComponent(txtIQ4)
                    .addComponent(txtIQ5)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel23)
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIQ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIQ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setMaximumSize(new java.awt.Dimension(109, 126));
        jPanel7.setMinimumSize(new java.awt.Dimension(109, 126));

        jLabel24.setText("Unit Price");

        lblUP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUP1.setEnabled(false);

        lblUP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUP2.setEnabled(false);

        lblUP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUP3.setEnabled(false);

        lblUP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUP4.setEnabled(false);

        lblUP5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUP5.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUP4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUP5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel24)
                .addGap(31, 31, 31))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUP1)
                .addGap(21, 21, 21)
                .addComponent(lblUP2)
                .addGap(18, 18, 18)
                .addComponent(lblUP3)
                .addGap(18, 18, 18)
                .addComponent(lblUP4)
                .addGap(18, 18, 18)
                .addComponent(lblUP5)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setMaximumSize(new java.awt.Dimension(102, 126));
        jPanel8.setMinimumSize(new java.awt.Dimension(102, 126));

        jLabel38.setText("Total Price");

        lblTP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTP1.setEnabled(false);

        lblTP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTP2.setEnabled(false);

        lblTP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTP3.setEnabled(false);

        lblTP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTP4.setEnabled(false);

        lblTP5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTP5.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTP4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTP5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel38)
                .addGap(33, 33, 33))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTP1)
                .addGap(21, 21, 21)
                .addComponent(lblTP2)
                .addGap(18, 18, 18)
                .addComponent(lblTP3)
                .addGap(18, 18, 18)
                .addComponent(lblTP4)
                .addGap(18, 18, 18)
                .addComponent(lblTP5)
                .addContainerGap())
        );

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Issue");
        jButton3.setToolTipText("Do you want to Issue the Items ?");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.setToolTipText("Reset everythings");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Lending ID", "Group No", "Customer ID", "Date", "Time", "Item No", "Qty", "Item No", "Qty", "Item No", "Qty", "Item No", "Qty", "Item No", "Qty"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable1);

        jLabel12.setText("Total Price of Issue Quantity      :");

        jLabel17.setText("Total No of Issue Quantity         :");

        jLabel55.setText("Lending ID");

        jButton6.setBackground(new java.awt.Color(0, 51, 51));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Check");
        jButton6.setToolTipText("Check the lend item details");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 153, 255));
        jButton7.setText("Demo");
        jButton7.setToolTipText("Demo to test");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNOIQ, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12)
                        .addGap(7, 7, 7)
                        .addComponent(lblNOIQP, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSID, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(lblSID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblNOIQ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNOIQP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton4)
                                .addComponent(jButton7)
                                .addComponent(jButton6))))
                    .addComponent(jScrollPane2))
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Reset() {

        txtSGN.setText("");
        lblSGL.setText("");
        lblEID.setText("");
        lblTP.setText("");
        lblCName.setText("");
        txtCID.setText("");
        lblCTP.setText("");
        lblAddress.setText("");
        lblM1.setText("");
        lblM2.setText("");
       
        lblEID1.setText("");
        lblEID2.setText("");
        
        jButton3.setVisible(false);
        
        lblIN1.setText("");
        lblIN2.setText("");
        lblIN3.setText("");
        lblIN4.setText("");
        lblIN5.setText("");
        txtIQ1.setText("");
        txtIQ2.setText("");
        txtIQ3.setText("");
        txtIQ4.setText("");
        txtIQ5.setText("");
        lblUP1.setText("");
        lblUP2.setText("");
        lblUP3.setText("");
        lblUP4.setText("");
        lblUP5.setText("");
        lblTP1.setText("");
        lblTP2.setText("");
        lblTP3.setText("");
        lblTP4.setText("");
        lblTP5.setText("");
        cmb1.setSelectedIndex(0);
        cmb2.setSelectedIndex(0);
        cmb3.setSelectedIndex(0);
        cmb4.setSelectedIndex(0);
        cmb5.setSelectedIndex(0);
        lblNOIQ.setText("");
        lblNOIQP.setText("");
    }
    
    public void incre() {
           try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM lending_returning_details");
            while (rs.next()) {

                String ab = rs.getString("lr_no");
                int ps = Integer.parseInt(ab);
                int ks = ps+1;
                 String ks1 = String.valueOf(ks);
                 lblSID.setText(ks1);
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Lending ID");
            
        }   
    }
    
    
    private void txtIQ1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIQ1KeyTyped
       char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtIQ1KeyTyped

    private void txtIQ2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIQ2KeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtIQ2KeyTyped

    private void txtIQ3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIQ3KeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtIQ3KeyTyped

    private void txtIQ4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIQ4KeyTyped
       char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtIQ4KeyTyped

    private void txtIQ5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIQ5KeyTyped
        char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)) {
           evt.consume();
       }
    }//GEN-LAST:event_txtIQ5KeyTyped

     public void table() {

        DefaultTableModel dtf = (DefaultTableModel) jTable1.getModel();
        dtf.setRowCount(0);

        try {
                Connection conn = DBconnect.connect();
                Statement s = conn.createStatement();
            
            rs=s.executeQuery("SELECT * FROM lending_returning_details");

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("lr_no"));
                v.add(rs.getString("group_no"));
                v.add(rs.getString("customer_id"));
                v.add(rs.getString("lend_date"));
                v.add(rs.getString("lend_time"));
                v.add(rs.getString("item_no1"));
                v.add(rs.getString("qty1"));
                v.add(rs.getString("item_no2"));
                v.add(rs.getString("qty2"));
                v.add(rs.getString("item_no3"));
                v.add(rs.getString("qty3"));
                v.add(rs.getString("item_no4"));
                v.add(rs.getString("qty4"));
                v.add(rs.getString("item_no5"));
                v.add(rs.getString("qty5"));
          
                            
                dtf.addRow(v);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Table load Fail");
        }
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txtCID.getText().isEmpty()) {
           JOptionPane.showMessageDialog(null, "Please Enter Customer ID"); 
        }
        else {
        try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM customer WHERE id='" + txtCID.getText() + "'");
            while (rs.next()) {

                lblCName.setText(rs.getString("last_name"));
                lblCTP.setText(rs.getString("contact_number"));
                lblAddress.setText(rs.getString("address_line2"));
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            
        }        
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Reset();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1ActionPerformed

boolean enable = cmb1.getSelectedItem().equals("Item 001") ||cmb1.getSelectedItem().equals("Item 002") || cmb1.getSelectedItem().equals("Item 003") || cmb1.getSelectedItem().equals("Item 004") || cmb1.getSelectedItem().equals("Item 005")|| cmb1.getSelectedItem().equals("Item 005")|| cmb1.getSelectedItem().equals("Item 006")|| cmb1.getSelectedItem().equals("Item 007")|| cmb1.getSelectedItem().equals("Item 008") ;
       txtIQ1.setEnabled(enable);
        
        try {
          
            
            Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
            rs=s.executeQuery("SELECT * FROM stock_details WHERE item_no='"+ cmb1.getSelectedItem().toString() + "'");
            while (rs.next()) {

                lblIN1.setText(rs.getString("item_name"));
                lblUP1.setText(rs.getString("selling_price"));
               
         }
            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cmb1ActionPerformed

    private void cmb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb2ActionPerformed

        boolean enable = cmb2.getSelectedItem().equals("Item 001") ||cmb2.getSelectedItem().equals("Item 002") || cmb2.getSelectedItem().equals("Item 003") || cmb2.getSelectedItem().equals("Item 004") || cmb2.getSelectedItem().equals("Item 005")|| cmb2.getSelectedItem().equals("Item 005")|| cmb2.getSelectedItem().equals("Item 006")|| cmb2.getSelectedItem().equals("Item 007")|| cmb2.getSelectedItem().equals("Item 008") ;
       txtIQ2.setEnabled(enable);
        
        try {
         Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
            rs=s.executeQuery("SELECT * FROM stock_details WHERE item_no='"+ cmb2.getSelectedItem().toString() + "'");
            while (rs.next()) {

                lblIN2.setText(rs.getString("item_name"));
                lblUP2.setText(rs.getString("selling_price"));
            }
    
         
            
        } catch (Exception e) {
}
    }//GEN-LAST:event_cmb2ActionPerformed

    private void cmb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb3ActionPerformed

        boolean enable = cmb3.getSelectedItem().equals("Item 001") ||cmb3.getSelectedItem().equals("Item 002") || cmb3.getSelectedItem().equals("Item 003") || cmb3.getSelectedItem().equals("Item 004") || cmb3.getSelectedItem().equals("Item 005")|| cmb3.getSelectedItem().equals("Item 005")|| cmb3.getSelectedItem().equals("Item 006")|| cmb3.getSelectedItem().equals("Item 007")|| cmb3.getSelectedItem().equals("Item 008") ;
       txtIQ3.setEnabled(enable);
      
        try {
         Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
            rs=s.executeQuery("SELECT * FROM stock_details WHERE item_no='"+ cmb3.getSelectedItem().toString() + "'");
            while (rs.next()) {

                lblIN3.setText(rs.getString("item_name"));
                lblUP3.setText(rs.getString("selling_price"));
            }
    
         
            
        } catch (Exception e) {
}
    }//GEN-LAST:event_cmb3ActionPerformed

    private void cmb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb4ActionPerformed

boolean enable = cmb4.getSelectedItem().equals("Item 001") ||cmb4.getSelectedItem().equals("Item 002") || cmb4.getSelectedItem().equals("Item 003") || cmb4.getSelectedItem().equals("Item 004") || cmb4.getSelectedItem().equals("Item 005")|| cmb4.getSelectedItem().equals("Item 005")|| cmb4.getSelectedItem().equals("Item 006")|| cmb4.getSelectedItem().equals("Item 007")|| cmb4.getSelectedItem().equals("Item 008") ;
       txtIQ4.setEnabled(enable);
        try {
         Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
            rs=s.executeQuery("SELECT * FROM stock_details WHERE item_no='"+ cmb4.getSelectedItem().toString() + "'");
            while (rs.next()) {

                lblIN4.setText(rs.getString("item_name"));
                lblUP4.setText(rs.getString("selling_price"));
            }
    
         
            
        } catch (Exception e) {
}
    }//GEN-LAST:event_cmb4ActionPerformed

    private void cmb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb5ActionPerformed
        
        boolean enable = cmb5.getSelectedItem().equals("Item 001") ||cmb5.getSelectedItem().equals("Item 002") || cmb5.getSelectedItem().equals("Item 003") || cmb5.getSelectedItem().equals("Item 004") || cmb5.getSelectedItem().equals("Item 005")|| cmb5.getSelectedItem().equals("Item 005")|| cmb5.getSelectedItem().equals("Item 006")|| cmb5.getSelectedItem().equals("Item 007")|| cmb5.getSelectedItem().equals("Item 008") ;
       txtIQ5.setEnabled(enable);
        try {
         Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
            rs=s.executeQuery("SELECT * FROM stock_details WHERE item_no='"+ cmb5.getSelectedItem().toString() + "'");
            while (rs.next()) {

                lblIN5.setText(rs.getString("item_name"));
                lblUP5.setText(rs.getString("selling_price"));
            }
    
         
            
        } catch (Exception e) {
}
    }//GEN-LAST:event_cmb5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtSGN.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Service Group ID");
        }
        
        else {
        
        try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM service_group_details WHERE group_no='" + txtSGN.getText() + "'");
            while (rs.next()) {

                lblSGL.setText(rs.getString("leader_name"));
                lblEID.setText(rs.getString("leader_empno"));
                lblTP.setText(rs.getString("leader_tp"));
                lblM1.setText(rs.getString("member1_name"));
                lblM2.setText(rs.getString("member2_name"));
               
                lblEID1.setText(rs.getString("member1_empno"));
                lblEID2.setText(rs.getString("member2_empno"));
              
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
        } 
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(txtSGN.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please Enter Service Group ID");    
        }
        
        else if (txtCID.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please Enter Customer ID");        
                }
        
        else if (lblSGL.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select valid service group");    
        }
        else if (lblCName.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select valid customer");    
        }
        else {
        try { 
             
            String sql ="INSERT INTO lending_returning_details(lr_no,group_no,customer_id,lend_date,lend_time,item_no1,qty1,item_no2,qty2,item_no3,qty3,item_no4,qty4,item_no5,qty5) VALUES ('"+lblSID.getText()+"','"+txtSGN.getText()+"','"+txtCID.getText()+"','"+lblDate.getText()+"','"+lblTime.getText()+"','"+cmb1.getSelectedItem().toString()+"','"+txtIQ1.getText()+"','"+cmb2.getSelectedItem().toString()+"','"+txtIQ2.getText()+"','"+cmb3.getSelectedItem().toString()+"','"+txtIQ3.getText()+"','"+cmb4.getSelectedItem().toString()+"','"+txtIQ4.getText()+"','"+cmb5.getSelectedItem().toString()+"','"+txtIQ5.getText()+"')";
            pst = con.prepareStatement(sql);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Saved Successfully");
      
        table();
          Reset();
          incre();
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Data save Failed");
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         
        jButton3.setVisible(true);
        
        if(txtIQ1.getText().isEmpty()) {
            txtIQ1.setText("0");
        }
         if(txtIQ2.getText().isEmpty()) {
            txtIQ2.setText("0");
        }
         if(txtIQ3.getText().isEmpty()) {
            txtIQ3.setText("0");
        }
         if(txtIQ4.getText().isEmpty()) {
            txtIQ4.setText("0");
        }
         if(txtIQ5.getText().isEmpty()) {
            txtIQ5.setText("0");
        }
         if(lblUP1.getText().isEmpty()) {
            lblUP1.setText("0");
        }
         if(lblUP2.getText().isEmpty()) {
            lblUP2.setText("0");
        }
         if(lblUP3.getText().isEmpty()) {
            lblUP3.setText("0");
        }
         if(lblUP4.getText().isEmpty()) {
            lblUP4.setText("0");
        }
         if(lblUP5.getText().isEmpty()) {
            lblUP5.setText("0");
        }
         
         String up11 = txtIQ1.getText();
         String up22 = txtIQ2.getText();
         String up33 = txtIQ3.getText();
         String up44 = txtIQ4.getText();
         String up55 = txtIQ5.getText();
        
         String Q1 = lblUP1.getText();
         String Q2 = lblUP2.getText();
         String Q3 = lblUP3.getText();
         String Q4 = lblUP4.getText();
         String Q5 = lblUP5.getText();
         
         double ss1 = Double.parseDouble(up11);
         double ss2 = Double.parseDouble(up22);
         double ss3 = Double.parseDouble(up33);
         double ss4 = Double.parseDouble(up44);
         double ss5 = Double.parseDouble(up55);
         
         double tot = ss1 + ss2 + ss3 + ss4 + ss5 ;
         
         double QQ1 = Double.parseDouble(Q1);
         double QQ2 = Double.parseDouble(Q2);
         double QQ3 = Double.parseDouble(Q3);
         double QQ4 = Double.parseDouble(Q4);
         double QQ5 = Double.parseDouble(Q5);
         
         double ssQQ1 = ss1*QQ1;
         double ssQQ2 = ss2*QQ2;
         double ssQQ3 = ss3*QQ3;
         double ssQQ4 = ss4*QQ4;
         double ssQQ5 = ss5*QQ5;
         
         double pri = ssQQ1 + ssQQ2 + ssQQ3 + ssQQ4 + ssQQ5;
         
         String sQ1 = String.valueOf(ssQQ1);
         String sQ2 = String.valueOf(ssQQ2);
         String sQ3 = String.valueOf(ssQQ3);
         String sQ4 = String.valueOf(ssQQ4);
         String sQ5 = String.valueOf(ssQQ5);
         
         String tot1 = String.valueOf(tot);
         String pri1 = String.valueOf(pri);
         
         lblTP1.setText(sQ1);
         lblTP2.setText(sQ2);
         lblTP3.setText(sQ3);
         lblTP4.setText(sQ4);
         lblTP5.setText(sQ5);
         
         lblNOIQ.setText(tot1);
         lblNOIQP.setText(pri1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
/*        lblSID.setText("1");
        txtSGN.setText("3");
        lblSGL.setText("Nimal Disanayake");
        lblEID.setText("006");
        lblTP.setText("07276376834");

        lblCName.setText("Samantha Silva");
        txtCID.setText("009");
        lblCTP.setText("0777344234");
        lblAddress.setText("Moratuwa");
        lblM1.setText("Namal Jayasinghe");
        lblM2.setText("Sandun Perera");
       
        lblEID1.setText("045");
        lblEID2.setText("086");
        */
        lblIN1.setText("Single Rod");
        lblIN2.setText("Double Rod");
        lblIN3.setText("Brass");
        lblIN4.setText("Clip Ring");
        lblIN5.setText("Holdback");
        txtIQ1.setText("4");
        txtIQ2.setText("3");
        txtIQ3.setText("5");
        txtIQ4.setText("4");
        txtIQ5.setText("4");
        lblUP1.setText("175.00");
        lblUP2.setText("240.00");
        lblUP3.setText("120.50");
        lblUP4.setText("55.00");
        lblUP5.setText("145.50");

        cmb1.setSelectedIndex(1);
        cmb2.setSelectedIndex(2);
        cmb3.setSelectedIndex(5);
        cmb4.setSelectedIndex(4);
        cmb5.setSelectedIndex(3);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtSGNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSGNKeyReleased
/*         
        if (txtSGN.getText().isEmpty()) {
            Reset();
        }
        else {
        try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM service_group_details WHERE group_no='" + txtSGN.getText() + "'");
            while (rs.next()) {

                lblSGL.setText(rs.getString("leader_name"));
                lblEID.setText(rs.getString("leader_empno"));
                lblTP.setText(rs.getString("leader_tp"));
                lblM1.setText(rs.getString("member1_name"));
                lblM2.setText(rs.getString("member2_name"));
               
                lblEID1.setText(rs.getString("member1_empno"));
                lblEID2.setText(rs.getString("member2_empno"));
              
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
        }
        } 
*/
    }//GEN-LAST:event_txtSGNKeyReleased

    private void txtCIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCIDKeyReleased
/*        
        if(txtCID.getText().isEmpty()) {
            Reset();
        }
        else {
        try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM customer WHERE id='" + txtCID.getText() + "'");
            while (rs.next()) {

                lblCName.setText(rs.getString("last_name"));
                lblCTP.setText(rs.getString("contact_number"));
                lblAddress.setText(rs.getString("address_line2"));
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
            
        }        
        } 
*/
    }//GEN-LAST:event_txtCIDKeyReleased

    private void txtSGNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSGNKeyPressed
 if(evt.getKeyCode()==KeyEvent.VK_ENTER) {      
        try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM service_group_details WHERE group_no='" + txtSGN.getText() + "'");
            while (rs.next()) {

                lblSGL.setText(rs.getString("leader_name"));
                lblEID.setText(rs.getString("leader_empno"));
                lblTP.setText(rs.getString("leader_tp"));
                lblM1.setText(rs.getString("member1_name"));
                lblM2.setText(rs.getString("member2_name"));
               
                lblEID1.setText(rs.getString("member1_empno"));
                lblEID2.setText(rs.getString("member2_empno"));
              
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");
        } 
 }    
 else {
     lblSGL.setText("");
     lblEID.setText("");
     lblTP.setText("");
     lblM1.setText("");
     lblM2.setText("");
     lblEID1.setText("");
     lblEID2.setText("");
 } 
 
    }//GEN-LAST:event_txtSGNKeyPressed

    private void txtCIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCIDKeyPressed
 if(evt.getKeyCode()==KeyEvent.VK_ENTER) {      
        try {
            
             Connection conn = DBconnect.connect();
               Statement s = conn.createStatement();
             
            rs = s.executeQuery("SELECT * FROM customer WHERE id='" + txtCID.getText() + "'");
            while (rs.next()) {

                lblCName.setText(rs.getString("last_name"));
                lblCTP.setText(rs.getString("contact_number"));
                lblAddress.setText(rs.getString("address_line2"));
         }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Customer ID");

        }
    }//GEN-LAST:event_txtCIDKeyPressed
 else {
     lblCName.setText("");
     lblCTP.setText("");
     lblAddress.setText("");
 }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb1;
    private javax.swing.JComboBox<String> cmb2;
    private javax.swing.JComboBox<String> cmb3;
    private javax.swing.JComboBox<String> cmb4;
    private javax.swing.JComboBox<String> cmb5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea lblAddress;
    private javax.swing.JLabel lblCName;
    private javax.swing.JLabel lblCTP;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEID;
    private javax.swing.JLabel lblEID1;
    private javax.swing.JLabel lblEID2;
    private javax.swing.JLabel lblIN1;
    private javax.swing.JLabel lblIN2;
    private javax.swing.JLabel lblIN3;
    private javax.swing.JLabel lblIN4;
    private javax.swing.JLabel lblIN5;
    private javax.swing.JLabel lblM1;
    private javax.swing.JLabel lblM2;
    private javax.swing.JLabel lblNOIQ;
    private javax.swing.JLabel lblNOIQP;
    private javax.swing.JLabel lblSGL;
    private javax.swing.JLabel lblSID;
    private javax.swing.JLabel lblTP;
    private javax.swing.JLabel lblTP1;
    private javax.swing.JLabel lblTP2;
    private javax.swing.JLabel lblTP3;
    private javax.swing.JLabel lblTP4;
    private javax.swing.JLabel lblTP5;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUP1;
    private javax.swing.JLabel lblUP2;
    private javax.swing.JLabel lblUP3;
    private javax.swing.JLabel lblUP4;
    private javax.swing.JLabel lblUP5;
    private javax.swing.JTextField txtCID;
    private javax.swing.JTextField txtIQ1;
    private javax.swing.JTextField txtIQ2;
    private javax.swing.JTextField txtIQ3;
    private javax.swing.JTextField txtIQ4;
    private javax.swing.JTextField txtIQ5;
    private javax.swing.JTextField txtSGN;
    // End of variables declaration//GEN-END:variables
}
